### ISSUE TITLE
Gradle upgrade

### ISSUE THREAD

**Issue by criticalAY** [CatimaLoyalty/Android#1022]
Should we not upgrade the Gradle and the libraries used in it. I tried but the project fails the test because of it.

**Comment by TheLastProject** [comment]
As written in #973, Gradle upgrades are currently blocked by a Weblate issue. Once that gets resolved I'm planning to upgrade Gradle and the other libraries that need a newer Gradle version.

For now though, that's not a possibility (at least, not without disabling some lint rules which increases the chance of accidentally introducing bad translations that can crash the whole app for some users a risk I'm not willing to take).

**Comment by criticalAY** [comment]
> As written in #973, Gradle upgrades are currently blocked by a Weblate issue. Once that gets resolved I'm planning to upgrade Gradle and the other libraries that need a newer Gradle version.
> 
> For now though, that's not a possibility (at least, not without disabling some lint rules which increases the chance of accidentally introducing bad translations that can crash the whole app for some users a risk I'm not willing to take).

ok got it thank you

**Comment by criticalAY** [comment]
@TheLastProject sorry I am writing this here but can we add a widget that shows a group of bar codes like a list where we can add or remove the desired item?

**Comment by Altonss** [comment]
> @TheLastProject sorry I am writing this here but can we add a widget that shows a group of bar codes like a list where we can add or remove the desired item?

I have opened a PR here #669 that enables a widget to directly open a group, unfortunately it still needs some tweaks (but haven't got the time currently, will work on it later...)
