### ISSUE TITLE
Improve settings screen

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1024]
The settings screen currently has several design flaws:

1. Everything is grouped under "User interface", this should be grouped into several different logical groups.
2. Only "Max. font size" has the current value displayed below it, all settings should

**Comment by Shanta-11** [comment]
Hello, I would like to work on this, can you assign it to me

**Comment by TheLastProject** [comment]
Done, have fun @Shanta-11 :)

**Comment by Shanta-11** [comment]
@TheLastProject 
Can you list out some category names I can use

**Comment by Shanta-11** [comment]
> Done, have fun @Shanta-11 :)

Do suggest some improvements if there are any
