### ISSUE TITLE
Offer import when users click on supported import files

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1025]
We want to register Catima as an opener for common import file names so that users can easily start an import.

For Catima: catima.zip
For Fidme: fidme-export-request-*.zip
For Loyalty Card Keychain: LoyaltyCardKeychain.csv
For Stocard: *-sync.zip
For Voucher Vault: vouchervault.json

When the user opens such a file, Android should offer "Import data into Catima" as option. Catima should select the correct importer based on the filename.

**Comment by TomerPacific** [comment]
Hey @TheLastProject , would you need assistance with this issue? I'd like to help out and get any background details needed to start working on this.

**Comment by TheLastProject** [comment]
It's mostly a time issue for me, just too many issues, so help would be great :)

As I understand it it should basically be about adding a few intent-filters to the AndroidManifest.xml for the ImportExportActivity and then inside the ImportExportActivity respond to the intent (LoyaltyCardEditActivity should show some code about the kind of data that'll be in the intent).

**Comment by TomerPacific** [comment]
Ok, I'll start working on this and update you on my progress.

**Comment by TomerPacific** [comment]
@TheLastProject  - Any way I can (easily) generate/create/get the different file types so I can test out that my intent filters work?

**Comment by Altonss** [comment]
> @TheLastProject - Any way I can (easily) generate/create/get the different file types so I can test out that my intent filters work?

You can maybe have a look at this https://github.com/CatimaLoyalty/Android/tree/master/app/src/test/res/protect/card_locker

**Comment by TomerPacific** [comment]
@TheLastProject  - Would you be able to approve/reject what I have written in my comment above? Want to make sure I am on the right path.

**Comment by TheLastProject** [comment]
Ah, I didn't get an email notification for your question because you added it after your original message so I missed it :)

> Also, just to make sure I am in the right direction, you want the functionality to work inside the ImportExportActivity after a user presses the Import From Filesystem button?

That seems the most logical place yeah, hooking it into the Activity instead of the task means that we you could easily hook into the existing logic for asking for a password and everything too.

**Comment by TomerPacific** [comment]
@TheLastProject , thanks for the feedback.
I looked at the files @Altonss suggested, but I think I need a more encompassing repository of different files types to test out that the code I added works.

Just as a preview, I added the following for importing zip files:

` <activity
            android:name=".ImportExportActivity"
            android:label="@string/importExport"
            android:exported="false"
            android:theme="@style/AppTheme.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:mimeType="application/x-zip-compressed" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <data
                    android:scheme="file"
                    android:host="*"
                    android:pathPattern=".*\.zip" />
            </intent-filter>
` 

I'll add a regex to enforce the files names you listed above.
I read that android's [pathPattern ](https://developer.android.com/guide/topics/manifest/data-element#path)is "regex-like" and can have a bit of boilerplate code to match things.

**Comment by TheLastProject** [comment]
> I looked at the files @Altonss suggested, but I think I need a more encompassing repository of different files types to test out that the code I added works.

Loyalty Card Keychain / Catima v1 is inlined in the code:
https://github.com/CatimaLoyalty/Android/blob/78348a6f9ca7c718e087010f59934840dc8bf625/app/src/test/java/protect/card_locker/ImportExportTest.java#L985-L1009

same with Voucher Vault:
https://github.com/CatimaLoyalty/Android/blob/78348a6f9ca7c718e087010f59934840dc8bf625/app/src/test/java/protect/card_locker/ImportExportTest.java#L1267-L1291

I totally understand that does make it harder to discover though, they should probably be moved to their own files to make the tests easier to understand and the test files easier to re-use.

> Just as a preview, I added the following for importing zip files:
> I'll add a regex to enforce the files names you listed above.
> I read that android's [pathPattern ](https://developer.android.com/guide/topics/manifest/data-element#path)is "regex-like" and can have a bit of boilerplate code to match things.

That sounds great :)

**Comment by TomerPacific** [comment]
@TheLastProject , thanks for your quick response.

I'm a bit confused about something.
In the **_ImportExportActivity_**, you have already set up logic to have handlers to deal with every file type you want to import.
I asked you previously if the user flow you want to happen is after a user clicks on the  _**Import From Filesystem button**_.

**So my question is, why do we need the intent filters?**

I thought (initially) that you wanted the application to be associated with specific files types, where if a user presses on them in his/her file manager, the Catima application will be presented as an option to open them (similar to an application that can open PDF files).

But as far as I understand from your most recent replies, this isn't the case. Because if a user can choose any file after pressing the Import From Filesystem button, there is no use for the intent filters here.

If I am wrong in my understanding, please correct me.

**Comment by TomerPacific** [comment]
Hi @TheLastProject, so I have been pounding my head against the wall for the last couple of days trying to find the correct string to put in the intent filter so it will only open zip/csv/json files according to what you have listed.
I've read through many SO questions and documentation and could not find a complete answer to how to open a specific file with an intent filter.

I've tried using pathPattern, pathPrefix, but nothing seems to work.

Below is the intent filter for zip files I have now:
```

 <intent-filter >
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType= "application/zip" />
                <data android:scheme="content"/>
                <data android:host="*"/>
 </intent-filter>
```

This does offer Catima as an option to open zip files:

![qemu-system-x86_64_IXaLTOn7sx](https://user-images.githubusercontent.com/23402988/196034131-6189e117-b0e9-41b7-8d7a-78c6d8287f31.png)

Regardless of that, I have added the following logic in the ImportExportActivity in the onCreate method (a bit rough right now, but it shows the direction):

```
Intent fileIntent = getIntent();
if (fileIntent != null && fileIntent.getType() != null) {
    String intentType = fileIntent.getType();
    if (intentType.contains("/zip")) {
       // This will have more logic for the different zip files
        importDataFormat = DataFormat.Catima;
    } else if (intentType.contains("/csv")) {
        importDataFormat = DataFormat.Stocard;
    } else if (intentType.contains("/json")) {
        importDataFormat = DataFormat.VoucherVault;
    }

    openFileForImport(fileIntent.getData(), null);
        }
```

If you have any idea how I can overcome the regex issue, I will appreciate it. 🙏 
Also, how can I easily create the different file types? You gave me the string equivalent inside the test classes, but I don't know how I can translate them to concrete files so I can try to import them.

**Comment by TheLastProject** [comment]
> I've read through many SO questions and documentation and could not find a complete answer to how to open a specific file name with an intent filter.
>
> I've tried using pathPattern, pathPrefix, but nothing seems to work.

Hmm, it's a shame that's apparently so difficult. I guess just grabbing all .zip, .json and .csv files would be an improvement then at least. In that case it'll be necessary to show all the import options when a file is opened, but that could be fine.

> Also, how can I easily create the different file types? You gave me the string equivalent inside the test classes, but I don't know how I can translate them to concrete files so I can try to import them.

Well those strings are the whole files, just with quoting to fit in Java files. Here they are with the quotes removed: [files.zip](https://github.com/CatimaLoyalty/Android/files/9795118/files.zip) (the Catima one is an old format not in the .zip, but still uses the Catima importer). The others are in https://github.com/CatimaLoyalty/Android/tree/master/app/src/test/res/protect/card_locker. The Catima .zip is missing, but that one is extremely easily generated by just using Export in the app itself.

**Comment by TomerPacific** [comment]
@TheLastProject  - I have opened a PR and am awaiting your review. I left a comment there regarding constants.
