### ISSUE TITLE
Add archive link below card list

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1038]
Currently, there is an "Archive" option in the overflow menu on the main screen.

It would be much nicer to have the link to the archive below the card list if an archive exists. Something like this:
![image](https://user-images.githubusercontent.com/1885159/191078615-73b512a2-b745-451b-8e32-1a74b87fde95.png)

There is already a string available to use for this: `viewArchivedCardsWithCount`.

---

Background:

This was originally implemented in #1009 but created a performance regression (#1026). It was therefore reverted in #1036 after a better performing attempt in #1029 had too many edge conditions.

This will need a pretty skilled Android developer.

**Comment by jmanan088** [comment]
Hey @TheLastProject  can i try this? Is this covered in hacktoberfest?

**Comment by TheLastProject** [comment]
Sure, every issue is covered under Hacktoberfest. This is quite a difficult issue though, I haven't been able to get this working myself without introducing performance regressions. So do be aware you're signing yourself up for quite a challenge here :sweat_smile:

**Comment by jmanan088** [comment]
@TheLastProject thank you for letting me know that. I will try if I won't be to solve it, then I'll let you know to de-assign the issue.

**Comment by jmanan088** [comment]
Hey @TheLastProject You can de-assign the issue. I'm pretty new to android and hence wasn't able to find how to any stuff in you repo.

**Comment by TheLastProject** [comment]
That's okay, thanks for the heads up :)

**Comment by dineshkarthi95** [comment]
Hey I can help with this issue, can you please assign this to me ?

**Comment by TheLastProject** [comment]
Sure, go ahead :)

**Comment by dineshkarthi95** [comment]
@TheLastProject Hey have raised a [PR](https://github.com/CatimaLoyalty/Android/pull/1114) for this feature. 

Hope this helps :)

**Comment by TheLastProject** [comment]
Closed in favor of #1477
