### ISSUE TITLE
FEATURE REQUEST: Automatic Balance Update

### ISSUE THREAD

**Issue by G-i-o** [CatimaLoyalty/Android#1044]
It would be useful to be able to add an expense to giftcards with balances without having to enter the edit form and calculate the new balance.

Something like a trolley icon on the preview page or under the displayed barcode/QR etc. Clicking on it would show a numeric pad where the expense could be typed and saved. On closure, the balance would be updated.

I am attaching a screenshot taken from a similar app with the same feature.

P.S. Your app is great with great features. **Thank YOU!** 
![photo_2022-09-23_11-03-29](https://user-images.githubusercontent.com/36502493/191927975-63b53568-58a6-4639-a451-cf9ccf9018a1.jpg)

**Comment by TheLastProject** [comment]
This seems great, helpful and simple to add.

I'm envisioning this as follows in the loyalty card view screen:
1. If the balance is more than 0, add a button in the bottom bar (maybe a cart icon?)
2. When pressing it, show a dialog like you showed

I think for the dialog we will want something like your screenshot, but maybe also show the current balance and balance left based on the number the user is entering.

**Comment by G-i-o** [comment]
Great. Thank You for the prompt response!

**Comment by polarhun** [comment]
HI @TheLastProject , I saw your project post on the hacktoberfest discord. I was wondering if this issue is still available and if I could pick it up?

**Comment by TheLastProject** [comment]
Go for it @polarhun :)

**Comment by TheLastProject** [comment]
Hey, I haven't heard any progress on this issue in over a week so I'm going to unassign it from you. Please tell me if you still want to work on it and I could re-assign you, but I want to prevent that like last Hacktoberfest a lot of issues get claimed and not finished this year. Nothing personal!

**Comment by polarhun** [comment]
Oh sorry for no updates, couldn't get around to wrapping up this week. I have written all of the logic on my fork already. I just need to sort out some UI tidbits, like the basket icon.

**Comment by TheLastProject** [comment]
Okay, no problem, re-assigned :)

**Comment by TheLastProject** [comment]
Fixed in #1073

**Comment by G-i-o** [comment]
Beautiful! Looking forward to see this as soon as
it appears on F-Droid.

Thank You!
