### ISSUE TITLE
Set card scanned with "Select image from gallery" as photo

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1057]
Most of the time when people are trying to import an image of their loyalty card from gallery, this is a high-quality image they'd also want to set as front/back photo. It would be good to automatically set it.

Expected workflow:
1. User goes to ScanActivity
2. Uses the "Select image from gallery" button
3. A barcode is found
4. If the front photo is empty, set the front photo to this photo (skip next steps)
5. If the back photo is empty, set the back photo to this photo (skip next steps)
6. Ask the user if they also want to replace the front or back photo with this image

We will need to think and test if this will feel correct when re-scanning. Perhaps a flag should be set on the front or back photo that the image was "automatically set" and thus can be overwritten in step 4 or 5 until the card is saved.

**Comment by tripathisharad** [comment]
Hello @TheLastProject can you assign this project to me I can try to solve the issue.

**Comment by TheLastProject** [comment]
Sure, go ahead :)

**Comment by liutng** [comment]
Hi, can I work on this issue since I saw this issue has no update for a quite while?

**Comment by TheLastProject** [comment]
Sure, go for it. I'm being quite slow with reviewing PRs currently though, I kinda burned myself out a bit during Hacktoberfest so I'm taking it slow. So do be aware it'll probably take some time to get a review (there's still several reviews pending too) :)

**Comment by liutng** [comment]
Sure, no worries. Thank you for letting me know. :)

**Comment by TheLastProject** [comment]
After rethinking, this adds too much code for something that most people won't care about and the others can do in just a few clicks. Catima is already getting quite complex for what it does and I need to prevent unnecessary complexity more.
