### ISSUE TITLE
Card info dialog style bugs

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1074]
After #1067 changed all dialogs to their Material counterpart, it became clear the padding of the card info dialog is kinda messed up and non-standard.

For context, it looks like this:
![image](https://user-images.githubusercontent.com/1885159/194717063-2b7670c6-f39b-403e-833b-b25ec411ad60.png)

It should look more like the credits dialog:
![image](https://user-images.githubusercontent.com/1885159/194717071-fd1f686c-2dec-46f4-89b8-6aa6113e18cd.png)

Labelling "good first issue" because most likely this will only require removing some padding and manual font size changes, but I don't currently have time to look too deeply into this.

**Comment by theseuntaylor** [comment]
hey @TheLastProject, I'd like to take this up.

**Comment by TheLastProject** [comment]
Sure, go for it :)

**Comment by TheLastProject** [comment]
Looks like @pfaffenrodt took this over, hope you don't mind (given Hacktoberfest is almost over and it's been 21 days since we heard from you)
