### ISSUE TITLE
Add an error message when user denied camera permission

### ISSUE THREAD

**Issue by liutng** [CatimaLoyalty/Android#1084]
Hi,
May I add a toast to show that the camera permission is not granted when the camera permission is denied?  I know this is going to be a very small change but this might be helpful when users forget they have chosen "never ask again" in the system permission dialog.

**Comment by shubhankar-bt** [comment]
Hii, i want to work on this issue

**Comment by liutng** [comment]
Thank you for your help, but I'll also provide a solution to this issue if I were allowed.

**Comment by TheLastProject** [comment]
Oh huh, I'm surprised I apparently never added that, that's a good idea indeed.

I think instead of a toast it would be much better if the ScanActivity could instead of a black screen with a toast show a message like:

> Camera permission not granted
>
> To scan barcodes, Catima will need access to your camera. Tap here to change your permission settings.

And on tapping that screen it should take you to Catima's permissions in Android (or Catima's app info).

It will be important to keep the import from file and enter manually buttons clickable no matter what, so that users who don't want to give Catima access to their camera can still use the app anyway (but manually). So I think something similar to the [home screen if you don't have cards yet](https://user-images.githubusercontent.com/1885159/195550956-5e41e5d2-7138-4408-9b3c-dd447fa54a42.png) would work best (it also allows you to still reach the + button, the main difference would be that this screen would be tap-able).

Because @liutng spotted this issue, I think it's fair if they get the chance to work on this first :)

**Comment by TheLastProject** [comment]
Ah, interesting, I wasn't aware Google doesn't recommend doing so. Specifically, their note seems to be "At the same time, respect the user's decision. Don't link to system settings in an effort to convince the user to change their decision."

I don't think we're disrespecting the user's decision given the UI has always been explicitly designed to explicitly offer "Select image from gallery" and "Manually enter ID" options that are just one click away and we're not bothering the users with dialog windows, just text on a screen in an user flow already designed to easily avoid it. However, Google's review team has always been extremely inconsistent so it's hard to know what they think. I'm also not sure right now how to nicely phrase the message if we're not allowed to help users who accidentally denied the permission.

I'm not completely sure how `PermissionRationale` works, it will need thorough testing to make sure the text is displayed whenever the camera permission is denied, but it does seem like it's the intended way to implement this so it is worth looking into.

**Comment by liutng** [comment]
Indeed. Google's review team has been inconsistent. 

Also, I tried to use PermissionRationale and noticed it will only show one single time after users denied the first permission access dialog, if users deny the permission twice,  ``` shouldShowRequestPermissionRationale() ``` will always return false. so ``` PermissionRationale ``` will never pop up again.

I think maybe it's better if we just stick with the solution you mentioned which is having the text in the center of the scanner view and I think it should be fine because we are not tempting users to click this line of text since users can always use the other 2 methods to add cards.

**Comment by TheLastProject** [comment]
> Also, I tried to use PermissionRationale and noticed it will only show one single time after users denied the first permission access dialog, if users deny the permission twice, shouldShowRequestPermissionRationale() will always return false. so PermissionRationale will never pop up again.

That's a shame, but thanks for testing.

> I think maybe it's better if we just stick with the solution you mentioned which is having the text in the center of the scanner view and I think it should be fine because we are not tempting users to click this line of text since users can always use the other 2 methods to add cards.

Sounds good, we'll just see what Google thinks during review. Worst case I end up removing the clickable part and slightly change the text :)

**Comment by liutng** [comment]
> That's a shame, but thanks for testing.
>
No worries, it's always good that we can analyze and fix the problem together.

> Sounds good, we'll just see what Google thinks during review. Worst case I end up removing the clickable part and slightly change the text :)
>
That would be the best solution for now and let's hope for the best.

I will test my code and hopefully create a Pull Request by the end of today.

Also, is that okay if I provide the Chinese version of the strings that I added to strings.xml since it's my native language? Or we should wait for someone on Weblate to translate for us?

**Comment by TheLastProject** [comment]
> Also, is that okay if I provide the Chinese version of the strings that I added to strings.xml since it's my native language? Or we should wait for someone on Weblate to translate for us?

Go for it, it is always helpful to have translations already be up-to-date :)
