### ISSUE TITLE
Empty state screen doesn't scale well

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1092]
![image](https://user-images.githubusercontent.com/1885159/196030078-813ba70f-a4f9-4a57-be98-a09f70ad82ca.png)

The text is cut off and you can't scroll. This also happens in the new ScanActivity layout in in #1085.

While this won't affect most users, it could possibly be annoying for users on devices with very small screens.

**Comment by liutng** [comment]
Can I work on this? And also I will fix the same problem in ScanActivity.

**Comment by TheLastProject** [comment]
Sure, that would be awesome :)

**Comment by liutng** [comment]
The fix has been submitted in PR #1095 .
