### ISSUE TITLE
Correct Importing Flow

### ISSUE THREAD

**Issue by TomerPacific** [CatimaLoyalty/Android#1102]
The in-app flow when importing a file to Catima is currently in the wrong order.

**Catima's in-app flow currently is**:

1. User opens Import/Export screen
2. User clicks Import From Filesystem
3. User is asked what type the import is
4. User selects file
5. User selects option and import starts

**The in-app flow should change to**:

1. User opens Import/Export screen
2. User clicks Import From Filesystem
3. User selects file
4. User is asked what type the import is
5. User selects option and import starts

Related to #1025

**Comment by TomerPacific** [comment]
Hey @TheLastProject,
I have opened a PR that I believes resolves this.
Let me know what you think.

**Comment by TheLastProject** [comment]
As explained in the PR, I was wrong, the flow was actually fine x.x I've been working way too hard during Hacktoberfest, seeing bugs where there weren't any, sorry x.x
