### ISSUE TITLE
Settings screen doesn't use Material Dialogs

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1129]
All the dialogs in the Settings screen use the old dialog style, no material dialogs yet. That should be fixed.

**Comment by Avito-Silva** [comment]
Hi. I want to help with this can you assign it?

**Comment by TheLastProject** [comment]
Sure, go ahead :) I'm working on another task myself right now that I want to "stay in the flow in" so it'll take me some days until I can really test it probably

**Comment by TheLastProject** [comment]
I think this is actually fixed, the dialogs have nice rounded corners for me. I'm closing this issue.
