### ISSUE TITLE
Add functionality to display image/photo in full screen mode

### ISSUE THREAD

**Issue by MartinRenze** [CatimaLoyalty/Android#1131]
The view for each card displays the saved photos only very small. The photo of my card contains additional information like a face picture and a name. They should be visible to the employee to whom I show the virtual Catima card. The displayed photo is to small to read the details on the card.

I propose to add a button that shows the added photos in full screen. If a button is not convenient for the UI a short or long press on the image could execute the full screen behavior.

Thanks for the awesome project.

**Comment by TheLastProject** [comment]
This should already be available by long-pressing the image in Catima 2.21.0 (added in #1052).

**Comment by MartinRenze** [comment]
Thank you for the very quick reply. Using f-droid i am still on 2.20.0. I'm looking forward to the update. Thanks!
