### ISSUE TITLE
Improve validation workflow on card

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1149]
When the group name is empty during group creation, Catima shows a message "Group name cannot be empty" right at the UI element where it's wrong:
![image](https://user-images.githubusercontent.com/1885159/205452977-dc3597fd-519d-48d7-aa40-1a7f92a84de7.png)

It would be good if it did this for the card creation/edit view too.

**Comment by TomerPacific** [comment]
Hi @TheLastProject ,
would you like help with this?

**Comment by TheLastProject** [comment]
You're free to work on it if you want, my main issue right now is that I got kinda burned out on working on Catima (I pushed myself way too hard during Hacktoberfest) and I haven't really found the time and energy to get back into it. I'm finally taking a vacation soon so hopefully that'll help me get some fresh energy :)

**Comment by TomerPacific** [comment]
@TheLastProject  - I hear you out. No point in working too hard and getting burned out.

Just wanted to help out here as I have already contributed to this repository with several issues.

I'll work on it and when you feel like you are fully recuperated, comment on the (future) PR.

Enjoy your vacation.

**Comment by Avito-Silva** [comment]
Hi what is the status of this issue?
