### ISSUE TITLE
Research reproducible builds

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1150]
Had a discussion with @obfusk, making Catima reproducible may be as easy as not using Android Studio to build and instead creating a shell script doing something like:

```
# Build release app
./gradlew assembleRelease
# Sort ZIP entries in APK
repro-apk sort-apk app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-unsigned-sorted.apk
# Sign the APK
apksigner -v sign --ks /path/to/my/keystore --ks-key-alias my-key-alias my.apk
```

Will need obfusk's [reproducible-apk-tools](https://github.com/obfusk/reproducible-apk-tools#sort-apkpy) and [apksigner](https://developer.android.com/studio/command-line/apksigner).

Worth spending some time trying, it could allow F-Droid users to update Catima outside of F-Droid too (for the impatient ones) and makes 100% clear that F-Droid didn't edit the APK (you know, unlike Google, who doesn't allow you to sign apps yourself anymore).

**Comment by TheLastProject** [comment]
Debugged this a bit more with @obfusk and it turns out the weird file order issue is caused by Android Studio and to build reproducibly all that's needed is to switch to the CLI and use Java 11:

```
$ export ANDROID_SDK_ROOT=$HOME/Android/Sdk
$ export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
$ ./gradlew clean assembleRelease
$ ./gradlew assembleRelease
$ apksigner -v sign --ks /path/to/my/keystore --ks-key-alias my-keyalias app/build/outputs/apk/release/app-release-unsigned.apk
```

**Comment by obfusk** [comment]
You're building twice with that script :sweat_smile:

It's either one command for clean + build combined:

```sh
$ ./gradlew clean assembleRelease
```

Or, if you prefer, two commands:

```
$ ./gradlew clean
$ ./gradlew assembleRelease
```

**Comment by TheLastProject** [comment]
Oops, thanks :)
