### ISSUE TITLE
Quick spend dialog doesn't use locale separator

### ISSUE THREAD

**Issue by pbda** [CatimaLoyalty/Android#1152]
In French, the decimal separator is comma (,). When you enter a balance with decimal part, a comma is required to have the right balance. It's OK. But when you enter a purchase with decimal part, it is not allowed to input a comma. Only dot is allowed but it is not recognized as decimal separator and the result is not correct.

**Comment by TheLastProject** [comment]
Oh wow, can't believe I missed this while reviewing that feature. That is a pretty bad bug.
