### ISSUE TITLE
[Feature Request] Import pkpass files

### ISSUE THREAD

**Issue by crapStone** [CatimaLoyalty/Android#1173]
I'd like to import [`.pkpass`](https://en.m.wikipedia.org/wiki/PKPASS) files into the app.

This is basically a format to share vouchers like cinema tickets.

**Comment by ProjectMoon** [comment]
You might want to look at https://github.com/CatimaLoyalty/Android/issues/48

**Comment by gv-sothebys-jeffverk** [comment]
See also: https://github.com/ligi/PassAndroid/

Old, but still works.

**Comment by crapStone** [comment]
I searched for it -.-
