### ISSUE TITLE
No migration possible (export -> import)

### ISSUE THREAD

**Issue by kangaroo72** [CatimaLoyalty/Android#1209]
Hi,
got the new S23 Ultra and want to move my data from my Note 10+ to the S23U.
Both versions are form Playstore 2.21.2 and the sync isn't working (no data in new app).
Tried also with FDroid-Version. Same Issue.

**Comment by kangaroo72** [comment]
Just tried something...
I'm using Nextcloud and transferred the backup with Nextcloud. After copying the backup to the local Download-Folder on my S23 the import was working.

**Comment by TheLastProject** [comment]
Interesting, do you still remember what you did when it didn't work?

**Comment by kangaroo72** [comment]
Yeah - I  made an export (catima.zip) and saved it to the Nextcloud-Folder in my Note 10+
On my S23 I've downloaded the backup via Nextcloud and made an import. That failed.
After copying the file to the folder "Downloads", it worked...

**Comment by TheLastProject** [comment]
I'm not sure what "downloaded the backup via Nextcloud and made an import" means and how it is different from downloading it normally.

If you want me to take a look into this I need to know step-by-step exactly which buttons you pressed where and if there were any error messages along the way. I don't currently have enough info to try to debug this.

**Comment by kangaroo72** [comment]
Thanks for investigating, but for me everything's okay now. we can close here. If someone reads this and is using Nextcloud too, he/she knows what to to.

Offtopic: Thanks for this lovely piece of software. I was using stocard before, but that is crap.... I love open source and data souveranity. Have a great time.
