### ISSUE TITLE
Export with/without images

### ISSUE THREAD

**Issue by guy-teube** [CatimaLoyalty/Android#1226]
Just an idea: add the possibility to export with/without the images (to have a lighter export file), for example to be dhared by e-mail, or faster daily sync on a cloud backup service.

**Comment by TheLastProject** [comment]
I don't really understand the use case of this. The images aren't that big and if they are not important enough for you to backup, I'd think they'd not be important enough to add to a card in the first place?

You can already use the share URLs, they don't support pictures yet.

**Comment by guy-teube** [comment]
Once I've got the images in a backup, there is no need to have them in the next ones, the updated csv is enough.

**Comment by TheLastProject** [comment]
This seems more easily solved by just deleting the old backup after you make a new one. I don't see this being useful for enough people to be worth making the app more complicated for, sorry.
