### ISSUE TITLE
[feature request] add an option to hide names on the main screen

### ISSUE THREAD

**Issue by ccrowles** [CatimaLoyalty/Android#1228]
As per title, it would be nice to have an option to not show the card names in the main grid screen and only leave the images, since people like me use the companies' logo as image, and so the text becomes redundant.

![Screenshot_20230303-120209_Catima](https://user-images.githubusercontent.com/12866474/222704239-f4129cad-76a1-4b74-aff1-e60d3812a3ba.png)

**Comment by Altonss** [comment]
This might be a duplicate of https://github.com/CatimaLoyalty/Android/issues/964

**Comment by ccrowles** [comment]
> This might be a duplicate of #964

Ah damn, I even searched for similar ones before opening this one. My bad, I'll close it.
