### ISSUE TITLE
Update Settings screen to use Material You design

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1263]
In Settings, all the Dialogs are not Material You. Also the Switches aren't Material You.

![image](https://user-images.githubusercontent.com/1885159/230725357-04686312-61cd-49ba-93ac-2aabc1213d1d.png)

Marked as "good first issue" not because I know how to do this, but because the scope is very minimal (just one activity) and should be very easy to test and not require any Catima-specific knowledge.

**Comment by pokegh0st** [comment]
Hi, I would like to take on this!

**Comment by TheLastProject** [comment]
Sure, good luck :)
