### ISSUE TITLE
Import from Stocard zip file won't works

### ISSUE THREAD

**Issue by ModellB** [CatimaLoyalty/Android#1277]
![Screenshot_20230417_174534_Catima](https://user-images.githubusercontent.com/131013795/232544446-624f56af-90ae-4d39-8113-d0d74f18caaf.jpg)

**Comment by ModellB** [comment]
Hello support team,

 

many thanks for reply. I've already get the import working by using the latest version on Catima. Because I has not configured automatic Android App updates, I has used the former version of Catima when I send you the error information. Later in the evening I checked for app updates and found the updated version of Catima which fixed the issue. Sorry for the inconvenience.

 

Best regards.

 

Theo

 
 

Gesendet: Montag, 17. April 2023 um 18:16 Uhr
Von: "Altonss" ***@***.***>
An: "CatimaLoyalty/Android" ***@***.***>
Cc: "ModellB" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [CatimaLoyalty/Android] Import from Stocard zip file won't works (Issue #1277)


 

Which version of Catima are you using? We had an issue with Stocard import #863 that got fixed since version 2.22.0 or higher.

**Comment by Altonss** [comment]
No worries :) I'm happy this solved your issue!
