### ISSUE TITLE
Changelog of v.2.22.0 missing on https://catima.app/changelog/

### ISSUE THREAD

**Issue by Altonss** [CatimaLoyalty/Android#1282]

**Comment by TheLastProject** [comment]
Thank you for the heads up, it broke when I renamed the default branch in the Website repo to `main`. I didn't notice that the daily rebuild was pointing to main.

And Netlify doesn't know that "success" and "failed" isn't the same ;)
| Netlify button | Job logs |
| - | - |
| ![image](https://user-images.githubusercontent.com/1885159/234565312-0c18795b-a1e1-4090-b805-152ed95ba4e0.png) | ![image](https://user-images.githubusercontent.com/1885159/234565359-c23f5d74-e5f4-4d78-a83c-eb4a41be85ca.png) |

Sadly, they didn't send me an email notification either. Apparently, it costs 19$ a month to get an email if the job fails. A bit more than I want to spend on such a simple website :)

I recreated the Netlify Build Hook to point to the correct branch (`main`) and triggered it manually this once. The CHANGELOG should now be automatically updated on a schedule again :)
