### ISSUE TITLE
F-Droid not building

### ISSUE THREAD

**Issue by Altonss** [CatimaLoyalty/Android#1318]
See: https://monitor.f-droid.org/builds/log/me.hackerchick.catima/121#site-footer
This is seems to be cause by a java version, similar to https://github.com/organicmaps/organicmaps/issues/5231

**Comment by obfusk** [comment]
Already [fixed in fdroiddata](https://gitlab.com/fdroid/fdroiddata/-/commit/cb97433f60b8c1630671b74e421c7bce4bb90951). We just need to wait for the next build cycle.

**Comment by Korb** [comment]
[CatimaLoyalty. No versions with compatible signer.jpg](https://drive.google.com/file/d/1utLoY9rsibtiiSqD2HIwGr8kvQbgyiS5/view) (screenshot @ Google Drive)

**Comment by TheLastProject** [comment]
@Korb That's not F-Droid not building. That is most likely Catima installed from another source signed with a different key (Google Play, IzzyOnDroid/GitHub). F-Droid signs it with their own key so you can't update between versions.

See also https://catima.app/faq/
