### ISSUE TITLE
Currency (¥) gets reset back to "Points" after adding a photo

### ISSUE THREAD

**Issue by obfusk** [CatimaLoyalty/Android#1322]
To reproduce:

1. set the currency to ¥, save.
2. add a photo (oddly, the currency is now listed as "JP¥", which is not normally in the list, in the options tab), save.
3. currency is now "points".

I can't reproduce it with e.g. €, only ¥ so far.

<details>
<summary>Normally</summary>

![Screenshot_20230530-160755_Catima cleaned](https://github.com/CatimaLoyalty/Android/assets/1260687/f77f44de-3318-4688-be8b-69869532c8cd)

</details>

<details>
<summary>After adding a photo, before saving</summary>

![Screenshot_20230530-160657_Catima cleaned](https://github.com/CatimaLoyalty/Android/assets/1260687/edfcfd46-2159-464e-af81-28bce0efefc7)

</details>

**Comment by obfusk** [comment]
I'd be happy to see if I can find the source of this bug. Unless you already have an idea.

**Comment by TheLastProject** [comment]
I think this may actually have to do with your locale. I can't reproduce it myself.

The currency code checks your system locale to figure out how to display the currency.

The bug is probably somewhere there, but not completely sure.

**Comment by obfusk** [comment]
I'll investigate more.

**Comment by obfusk** [comment]
I tried reproducing this in the Android emulator, but that only shows `JP¥`, not `¥` (for both Android 11 and 13 and using UK English). So it might be a bug in LineageOS. Weird.

**Comment by obfusk** [comment]
I updated LineageOS today and now I can't reproduce it on my phone either. It now only has `JP¥` and no `¥` as well.

Sorry about the noise.

**Comment by obfusk** [comment]
So... my phone (`en_GB` + `ja_JP`) still has only `JP¥` now. But my Android 13 emulator (`en_US`) now has `¥`.

And I can reproduce the bug on my phone again if I set Catima's language to Japanese.

This seems like an Android bug. But we may want to consider handling it if we can. I'll look into it later.

**Comment by obfusk** [comment]
So it looks like `en_GB` uses `JP¥`, but `en_US` and `ja_JP` use `¥`.
I can now reproduce this in the emulator if I set the system to `en_GB` and the app to `ja`.

**Comment by obfusk** [comment]
The issue seems to be caused by the default locale used by `Currency.getSymbol()` changing when using the gallery to select an image.

I've also witnessed the currency display in the main screen changing between `JP¥` to `¥` sometimes; not entirely sure what triggers that. And relatedly, half the app's UI will often still be in the previous language for a while after switching to a different one in settings.

Unfortunately, calling `Locale.getDefault()` will result in different values depending on when it's called, even if you're not selecting images; e.g. it's used in `LoyaltyCardEditActivity.attachBaseContext()` to set `mSystemLocale` (e.g. to `en_GB` in my case). But calling it in `onCreate()` gets me `ja` if I set the app to Japanese in the settings.

It would be nice to make sure it's consistently using the app locale everywhere it's displaying the currency. But I'm not 100% confident about detecting that properly without risking edge cases and/or bugs on different Android versions handling locales differently. Hence my proposed fix is to ignore the locale as such and simply cache the results to make sure they are consistent as the code requires them to be.

**Comment by TheLastProject** [comment]
> And relatedly, half the app's UI will often still be in the previous language for a while after switching to a different one in settings.

I've seen this too but I never figured out what causes it. Should probably try to move away from the internal language selector to the new Android method (#991) but doing this without breaking locale selection for older Android versions seems to not be documented by Google as far as I could tell which is frustrating.

> Unfortunately, calling Locale.getDefault() will result in different values depending on when it's called, even if you're not selecting images; e.g. it's used in LoyaltyCardEditActivity.attachBaseContext() to set mSystemLocale (e.g. to en_GB in my case). But calling it in onCreate() gets me ja if I set the app to Japanese in the settings.

Seems related to #761.

> It would be nice to make sure it's consistently using the app locale everywhere it's displaying the currency. But I'm not 100% confident about detecting that properly without risking edge cases and/or bugs on different Android versions handling locales differently. Hence my proposed fix is to ignore the locale as such and simply cache the results to make sure they are consistent when the code requires them to be; see https://github.com/CatimaLoyalty/Android/pull/1371.

That does make some sense.

**Comment by obfusk** [comment]
> Should probably try to move away from the internal language selector to the new Android method (https://github.com/CatimaLoyalty/Android/issues/991) but doing this without breaking locale selection for older Android versions seems to not be documented by Google as far as I could tell which is frustrating.

Please let me know how I can help with that, I'm happy to look into it (though it doesn't sound easy) :)
