### ISSUE TITLE
Not all external links in the about screen are easily identifiable as such

### ISSUE THREAD

**Issue by obfusk** [CatimaLoyalty/Android#1324]
All of these except for "Credits" open an external link in a browser. For buttons marked "on GitHub" and "on Weblate" that's expected, but it may be unexpected that "License", "Version History", and "Privacy Policy" open an external link, whereas "Credits" does not.

![Screenshot_20230530-141124_Catima cleaned](https://github.com/CatimaLoyalty/Android/assets/1260687/a1852b74-0159-41da-ba71-769b29130897)

**Comment by dubeyanant** [comment]
I can do this!

**Comment by obfusk** [comment]
@dubeyanant I don't think there's been a decision yet on whether this change should be implemented or not. But thanks.

**Comment by obfusk** [comment]
> Maybe a better start would be to make sure the License is included with Catima and displayed internally, so that's at least one less online thing.

I was thinking the same. Either make it obvious it's an external link (using a small symbol or text similar to the "on GitHub" for other buttons), or just include the License. Maybe also the Version History and the Privacy Policy? Apart from missing info about later versions I don't see why those can't be included in the app too.

**Comment by obfusk** [comment]
> I guess if we embed the privacy policy it may need a link to the online version just in case it ever needs changing

Since the app is entirely offline, I would assume the privacy policy at the time a version was built/published is "more correct" than a newer version which may reflect changes made to the app (e.g. which permissions it uses) since then that are not present in that version. The exception would be if the privacy policy contained a mistake that was fixed.

**Comment by obfusk** [comment]
> I have no clue how you'd embed an app's fastlane data into the app itself.

Me neither. But I can look into that if you'd like.

**Comment by obfusk** [comment]
Simply adding "The latest version of this privacy policy can be found at https://catima.app/privacy-policy/" or something similar to the privacy policy would seem to me to resolve all potential issues here.

**Comment by TheLastProject** [comment]
Sounds good. We can move the privacy policy into this repo and edit the website build script to download it from here so there is only one place to update it then 👍

**Comment by dubeyanant** [comment]
Can I help in any way?
