### ISSUE TITLE
Odd positioning of barcode

### ISSUE THREAD

**Issue by obfusk** [CatimaLoyalty/Android#1325]
Is this placement intentional? Because it looks odd to me that the barcode is not centred in the available space.

QR codes are also aligned to the top at small height, but become more centred at larger height, which seems inconsistent.

![Screenshot_20230530-143104_Catima cleaned](https://github.com/CatimaLoyalty/Android/assets/1260687/6badb7a5-b3fd-4b0f-8b69-beb1ca7a9c94)

**Comment by TheLastProject** [comment]
This is actually as intended, QR codes are the buggy one.

This screen exists for cases where there is only a limited amount of space to scan the barcode, so you want things as close to the edge of your screen as possible to increase the chance of being able to push part of your phone to where the scanner can see it.
