### ISSUE TITLE
Make barcode value text selectable

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1326]
Got an email today from an user wishing the ability to select barcode values to come back.

I'll be honest, I forgot this existed, I never used it.

However, given we now show the value in a pop-up anyway after clicking it (so values that are too long to fit in one line are still readable), we may as well make that text selectable:

![image](https://github.com/CatimaLoyalty/Android/assets/1885159/08ddf578-41d9-49c8-9292-18c35a089417)

**Comment by cristian-flavius** [comment]
Hello, can I work on this issue?

**Comment by obfusk** [comment]
@cristian-flavius I'm not involved in maintaining Catima so I hope @TheLastProject will correct me if I'm wrong, but AFAIK you're welcome to make a pull request. I would suggest reading the project's [CONTRIBUTING.md](https://github.com/CatimaLoyalty/Android/blob/main/CONTRIBUTING.md) first :)

**Comment by poorva-patidar** [comment]
Hello, I would like to work on this issue if anyone else is not working on it.

**Comment by obfusk** [comment]
Closed by #1331.
