### ISSUE TITLE
Square barcodes, landscape and full-screen views

### ISSUE THREAD

**Issue by Terrance** [CatimaLoyalty/Android#1332]
Whilst landscape orientation works well for 1D barcodes, it makes non-trivial 2D codes like Aztec render too small to use due to the surrounding screen furniture (action bar, bottom bar, ID as text and so on).

![Screenshot_2023-06-01-18-57-58-26_0e0fb5e4c7b0c70cd406dc034ad65059](https://github.com/CatimaLoyalty/Android/assets/4025899/7728e4fe-bbf3-4a59-9514-dee10bc4f0b2)

Here's one such example (value randomised but in the same format as a real ID, and the code is of comparable complexity).  At that size it's rather difficult to scan, meaning I need to jump into the full-screen view which is a bit more cumbersome.

The height slider also overlaps slightly with square codes in the landscape full-screen view when at the max value (i.e. lowest height), meaning you need to reduce it slightly to fit.

![Screenshot_2023-06-01-18-58-14-88_0e0fb5e4c7b0c70cd406dc034ad65059](https://github.com/CatimaLoyalty/Android/assets/4025899/f546189d-0636-49bf-9334-2625ea7d9db7)

It would be useful to have an option to force landscape for 1D codes and portrait for 2D, or otherwise to arrange the landscape view for 2D codes to place certain information beside them.  Alternatively, having separate orientation settings for the main and full-screen views would allow forcing landscape only in the full-screen view, where square codes fit better in either orientation.

**Comment by Terrance** [comment]
Device is a OnePlus Nord CE (running Android 12 if that's relevant), and the screen size is comparable with most current devices (6.43", 1080x2400).

> it's rather easy to just rotate your phone

Less so when I want it locked portrait for most apps and most of the time -- I'd either have to unlock the orientation lock when I want to pull up a code (and then lock it again), or rely on the corner button which the OS temporarily shows when it thinks the phone rotated (which tends to be rather finicky).

**Comment by TheLastProject** [comment]
24fe6886c9f726f8e3c71174cc39213aaec7c5bb should reduce the chance of the Height bar overlapping the barcode in landscape fullscreen. So that is part of this issue fixed.

**Comment by obfusk** [comment]
I'm looking into this now. Found some interesting things. Have a workaround of sorts. But trying to find the root cause.

**Comment by Terrance** [comment]
Just spotted this made it to a release -- works much better now, thanks!

![Screenshot_2023-07-16-09-26-50-25_0e0fb5e4c7b0c70cd406dc034ad65059](https://github.com/CatimaLoyalty/Android/assets/4025899/01152f2b-358b-497c-91a7-7968fbe33a2d)

**Comment by TheLastProject** [comment]
Thanks for confirming @obfusk's change works as intended :)
