### ISSUE TITLE
LoyaltyCardViewActivity shows cardId even if barcodeId is set

### ISSUE THREAD

**Issue by obfusk** [CatimaLoyalty/Android#1335]
It's possible to set the barcode value to something other than the card ID.

But both the text below the barcode as well as the "Barcode value" dialog that shows the full text unconditionally show `cardId` even if `barcodeId` is set.

I'll make a PR to use `barcodeId` if set.

**Comment by TheLastProject** [comment]
Card ID is the displayable value. By default, this is consistent with the Barcode value.

However, some stores put different data in the barcode itself than they display on the loyalty card.

By setting Card ID to a different value from Barcode value, users can have their, for example, customer number on the screen even if the barcode contains different values. See the issues labelled [store quirk](https://github.com/CatimaLoyalty/Android/labels/subject%3A%20store%20quirk).

**Comment by obfusk** [comment]
Makes sense. I wasn't entirely sure how this was used. I do think it's inconsistent that the dialog window is titled "Barcode value" (which is why I assumed that's what it should display) when that's not actually what's being displayed in those cases. Would it make sense to change that to "Card ID" then?

**Comment by TheLastProject** [comment]
Yeah, that's an oversight on my part. "Card ID" would've been the right name for that dialog window. That would also be more consistent with the home screen. I was rushing that dialog because it was a workaround for a critical regression already in production.

**Comment by obfusk** [comment]
I opened #1337.
