### ISSUE TITLE
Broken template for square screen

### ISSUE THREAD

**Issue by hooddy** [CatimaLoyalty/Android#1339]
Current version broke template for square screen like unihertz titan phones. Bar/qr codes dont fit.
![Screenshot_20230603-145125.png](https://github.com/CatimaLoyalty/Android/assets/6899176/a6cb99d3-ba27-47aa-af5f-cf34eb82ac67)

**Comment by hooddy** [comment]
Oh workaround is to make barcode landscape in settings. But its so strange coz screen is squared.
![Screenshot_20230603-145727~2.png](https://github.com/CatimaLoyalty/Android/assets/6899176/aa564879-16f7-44e2-acd0-537f346abd2b)

**Comment by TheLastProject** [comment]
Thanks for the report. This really sucks :( I'll try to fix it ASAP. I've never heard of this or any square-screened phones before, so I didn't test this (I have never tested any Catima change on a square screen).

I don't know if you get Catima from Google Play or F-Droid but it would be great if you could either join the [Google Play Open Testing](https://play.google.com/apps/testing/me.hackerchick.catima) program or use the [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index.php) repository (note: the software there is not all 100% open source, Izzy has less strict rules than F-Droid) on F-Droid to get updates more quickly. Having people on non-standard devices like these test updates earlier will help reduce the amount of people running into breakage.

**Comment by TheLastProject** [comment]
I think my most recent change should fix this. Could you please test the .apk file in the attached .zip file? If it works I'll create a new release so we can fix square screens quickly.

[app-debug.zip](https://github.com/CatimaLoyalty/Android/files/11642619/app-debug.zip)

**Comment by hooddy** [comment]
> I think [my most recent change](fb488af2b7df56a6558ccfd3de47346f2440871b) should fix this. Could you please test the .apk file in the attached .zip file? If it works I'll create a new release so we can fix square screens quickly.
> 
> [app-debug.zip](https://github.com/CatimaLoyalty/Android/files/11642619/app-debug.zip)
> 

Yep it is fixed. I download it from f-droid. Btw its common behav for apps. Vanced is the same. Imma create issue in it too...
![Screenshot_20230603-163536.png](https://github.com/CatimaLoyalty/Android/assets/6899176/9d72f468-add0-4a1c-8bbb-fe7082820e50)

**Comment by TheLastProject** [comment]
Thank you so much for the report and quick test, fixed in fb488af2b7df56a6558ccfd3de47346f2440871b then. Just released 2.23.3 with this fix, it'll be available in F-Droid in a few days, Izzy in probably about 2 hours and I'll start the rollout on Google whenever they're done reviewing it.
