### ISSUE TITLE
About dialog looks messy in RTL locales

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1362]
Some things seem to start on the left of the screen, others on the right. My first guess is that this is a marginLeft vs marginStart or paddingLeft vs paddingStart issue.

Specifically "on Weblate" under "Help translate" and "Copylefted libre software, licensed GPLv3+" under "License" seem wrongly aligned.

![image](https://github.com/CatimaLoyalty/Android/assets/1885159/2c4b246c-5738-44cf-ada3-57e8b70f40b4)

**Comment by CYBWEBALI** [comment]
Hey, I can fix this issue. Can you assign it to me.

**Comment by obfusk** [comment]
@CYBWEBALI Thanks! I already made a PR (#1364). I'm not an experienced Android dev though, so feel free to review it.
