### ISSUE TITLE
Can no longer install both debug and stable Catima installs

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1410]
My guess is this is caused by #1121, possibly by the permission: https://github.com/CatimaLoyalty/Android/pull/1121/files#diff-7fa6aef292187a049f7a4d6060d8df3ba212d838789c78940bd363344b1c38cd

After just building a new stable .apk when trying to release an update, the installation fails with the following message:
```
App not installed as package conflicts with an existing package.
```

![Screenshot showing above error message](https://github.com/CatimaLoyalty/Android/assets/1885159/02f11bba-b266-459a-ac09-e2dc852f0501)

Labelled as critical severity and frequent commonness as I need to be able to run both regular Catima (as I use it in my daily life) and debug Catima (for testing) and thus I cannot do a new release in the current state.

Ping @joserebelo :)

**Comment by joserebelo** [comment]
@TheLastProject I have both stable (self-built, with the permission) and debug versions installed, both with the permission :thinking: 

Not sure how to reproduce this, would you be able to send me the stable apk, or check logcat for the error?

**Comment by TheLastProject** [comment]
[app-release.zip](https://github.com/CatimaLoyalty/Android/files/11995140/app-release.zip)

Here's the new stable .apk I built today (that I planned to release).

logcat seems to imply that it is indeed the duplicate permission at fault here:
```
07-09 14:35:56.711  1641  1854 W PackageManager: Package me.hackerchick.catima attempting to redeclare permission me.hackerchick.catima.READ_CARDS already o
wned by me.hackerchick.catima.debug
07-09 14:35:56.716  1641  1854 D PackageInstallerSession: Marking session 1267431085 as failed: INSTALL_FAILED_DUPLICATE_PERMISSION: Package me.hackerchick.catima attempting to redeclare permission me.hackerchick.catima.READ_CARDS already owned by me.hackerchick.catima.debug
```

**Comment by joserebelo** [comment]
Interesting, it looks like the error only happens if the packages are signed by different keys, which is why I was able to have both installed :/

I'll open a PR in a few minutes.

**Comment by joserebelo** [comment]
PR open, I will do the necessary changes on the Gadgetbridge side later today, needs a slight refactor to request the permissions with the correct package name.

Apologies for the issue.. I completely forgot that some of these conflicts are allowed if the signature keys match.
