### ISSUE TITLE
Improve feature graphic

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1448]
The current Catima feature graphic is pretty bland and doesn't really invite people to try the app: https://github.com/CatimaLoyalty/Android/blob/main/fastlane/metadata/android/en-US/images/featureGraphic.png

![image](https://github.com/CatimaLoyalty/Android/assets/1885159/b88c10fc-3e8e-42a0-8c7e-1df995f0f2fa)

For comparison, Stocard actively promotes what the app is about (but with an app screenshot, if we go that way we need some automation to be able to update the screenshot without an image editor present), Google Wallet (wait, I thought it was Google Pay?) shows the name next to the logo so that people who don't know the logo can web search it.

![image](https://github.com/CatimaLoyalty/Android/assets/1885159/cc9f599c-c09e-4724-bc18-f412b15b0cad)

We should either like... add Catima's name (so people who don't know the logo will be able to search the web for the name) or use a slogan, something like "Your cards, your data. Private and offline."

**Comment by obfusk** [comment]
I'm not really a designer, but I'm happy to help if I can. Should be able to make something based on those suggestions. And I can look into automating updating the screenshot if we want one in the graphic.

**Comment by TheLastProject** [comment]
I think it's fine to wait for a designer, we'll have Hacktoberfest coming up in October too which gives us an increased chance of designers too.

**Comment by ziadOUA** [comment]
<br>

<p align="center">
  <img src="https://github.com/CatimaLoyalty/Android/assets/111606433/4905a29f-f4e6-4b36-8315-8289a5000b14" height="180px">
  <img src="https://github.com/CatimaLoyalty/Android/assets/111606433/9f2ed90c-6c34-4172-8a7d-e21b0df6292b" height="180px">
</p>

-----

Here is my concept, made in Figma using the open source font "Facifico".

**Comment by obfusk** [comment]
@ziadOUA I like it! Especially with the barcode. I do worry about the readability of the font though, e.g. for people with dyslexia or other visual disabilities etc. I personally find the "t" hard to read. I'm not an accessibility expert though. Just seems like something we'd want to consider before using it.

**Comment by ziadOUA** [comment]
Very legitimate issue 👍, I'll see what I can do.

**Comment by NajniFatima** [comment]
![Catima_New1](https://github.com/CatimaLoyalty/Android/assets/95522319/a5be8afc-960d-48bb-9d5a-04264f5393d1)


Give your feedback on this one :)

**Comment by TheLastProject** [comment]
They're both pretty, although I don't quite understand why the letter M is coloured differently as the letter M has no special meaning in the name (Catima stands for **Ca**rd and **ti**cket **ma**nager).

I personally prefer @ziadOUA's design currently, I guess the second one because I worry the first one will make people think Catima is a barcode scanner which it isn't really (sure, you scan barcodes to store cards but for scanning random barcodes there are much better apps available). Quite ironically, Catima fails to scan the barcode in the first image too 😅 

Thank you both a lot for contributing! I appreciate it a lot :)

**Comment by ziadOUA** [comment]
<br>

<p align="center">
  <img src="https://github.com/CatimaLoyalty/Android/assets/111606433/c6785338-b428-4f17-b681-78f11e646a84" height="180px">
  <img src="https://github.com/CatimaLoyalty/Android/assets/111606433/e548ce24-5422-4140-a930-dd0886f02960" height="180px">
</p>


-----

Not too sure about the font ("Yesteryear" -> Free for Personal and Commerical Use), but still worth being shown. Should solve the accessibility issue raised by the older design.

**Comment by TheLastProject** [comment]
I think the non-barcode version of Yesteryear looks nice enough. But I do think we have to lose the corners, Google or F-Droid's rounding might crop the corners differently than us and make it look ugly.

Do you have a SVG version of this by any change? It would be awesome to have something like "Loyalty Card Wallet" written below and if it's an SVG it would be translatable programmatically and we can keep all languages up-to-date automatically. If not, that's fine, I'll just use the non-barcode Yesteryear variant as-is, it's already an improvement :)

**Comment by ziadOUA** [comment]
I designed it on Figma, so exporting it in SVG will be easy. The only problem is that text doesn't get exported as text (<text>), but as a path (<path>). It could be done manually I guess.

**Comment by TheLastProject** [comment]
I have no experience with Figma, but a quick search seems to imply disabling "Outline text" might work to get a `<text>` element: https://forum.figma.com/t/how-do-i-export-the-text-property-out-of-figma-for-an-svg/754

If that doesn't work we can also just stick to the PNG. I don't want to put too much extra work on you, it just sounded like a nice feature to have an explanation of the app in every language :)

**Comment by ziadOUA** [comment]
It worked, 

<p align="center">
  <img height="190" src="https://github.com/CatimaLoyalty/Android/assets/111606433/9477216f-1d08-4801-80ef-70d69f70420a">
  <img height="190" src="https://github.com/CatimaLoyalty/Android/assets/111606433/5c087675-ac86-4b88-8643-e227a0706555">
</p>

PNG / SVG

**Comment by TheLastProject** [comment]
Thanks!

Looking inside the XML, it still says `font-family="Yesteryear"` and `font-family="Lexend Deca"`, so the SVG now depends on the fonts being installed on the user's system.

Now we have an interesting challenge: build a script that:
1. Ensures the fonts are available
2. Edits the text to the correct value
3. Generate the PNG with the font correct

I can try to spend some time getting this to work :) Thank you for your design help!

**Comment by ziadOUA** [comment]
It was my pleasure :)

**Comment by TheLastProject** [comment]
The new images are live on Google Play. F-Droid will sync next update. IzzyOnDroid I don't know actually when that updates metadata but will ping Izzy if not updated after next release :)

![Screenshot_20230903-145941_Fennec](https://github.com/CatimaLoyalty/Android/assets/1885159/57c0422f-8898-47ab-a83e-4e015edaee38)
