### ISSUE TITLE
Enhancement: Scan multiple at a time / create multiple cards from one image

### ISSUE THREAD

**Issue by e-t-l** [CatimaLoyalty/Android#1449]
How difficult would it be to add the ability for Catima to recognize, in a photo or image selected from gallery, that there are multiple codes present and create separate cards for each code (or perhaps only create separate cards for _unique_ codes)? The cards could be named with some basic formula (e.g. date + time + original image name if from gallery), which users would be able to rename or add info about afterwards.

The use case that inspired this was when I bought show tickets online, and the confirmation screen had four codes:
1. Ticket \#1's code as a QR
2. Ticket \#1's code as a barcode
3. Ticket \#2's code as a QR
4. Ticket \#2's code as a barcode

Currently, I have to screenshot the page, then crop the screenshot to show just one code at a time to add it to Catima.
It would be awesome if Catima could recognize this kind of image and create just two cards, aka one per ticket!

**Comment by TheLastProject** [comment]
I'd like to have as little magic as possible, definitely not auto-named cards, it would be very easy to get lost with those if you have many cards.

However, I do agree it would be good to detect multiple barcodes on a page. I'm thinking a flow like this could work best:

1. When selecting an image from gallery, Catima scans it for barcodes
2. If no barcodes are found, it shows the "no barcodes found" error (end of flow)
3. If exactly 1 barcode is found, it will start the card creation with that barcode (end of flow)
4. If more than 1 barcode is found, it shows all barcodes found (preferably it shows the whole image with the barcode areas highlighted, but if that's too hard or for a first prototype we can list them in another way). Clicking a barcode would open the card creation and after saving or cancelling you return to the overview image so you could create cards for other barcodes if you still want

**Comment by obfusk** [comment]
Do we have a way to scan an image for multiple barcodes? I may have missed that but I never saw a feature like that when working with zxing before.

**Comment by TheLastProject** [comment]
Looking at the code a bit, it seems that the [Result object zxing returns](https://github.com/CatimaLoyalty/Android/blob/72b8781eec71db5fe8088c64315715b53e8cca7b/app/src/main/java/protect/card_locker/Utils.java#L234) has a [resultPoints](https://github.com/zxing/zxing/blob/254d4df557702086e56d78924932d32b18eebf02/core/src/main/java/com/google/zxing/Result.java#L32) which [it defines as](https://github.com/zxing/zxing/blob/254d4df557702086e56d78924932d32b18eebf02/core/src/main/java/com/google/zxing/ResultPoint.java#L21): "Encapsulates a point of interest in an image containing a barcode. Typically, this would be the location of a finder pattern or the corner of the barcode, for example."

Assuming it'll scan top to bottom, left to right we could use this to:
1. Scan the image
2. Save the position of the first barcode
3. Truncate the image to the point where it doesn't contain the first barcode
4. Repeat until no more results

That feels a bit hacky though, but I can't think of better options.

**Comment by e-t-l** [comment]
That does feel hacky. I could easily imagine failure with, for example, a 2x2 grid of barcodes. It detects the upper left one first, crops the image vertically, and then misses the upper-right one. Or if it crops horizontally, it'll miss the lower-left one.

Sorry, didn't realize when I suggested this that the scanning was done entirely with a 3rd party API!

If it encapsulates the point of interest/corner/finder pattern, theoretically that's what it would use to determines what portion of the image contains the rest of the barcode. If there's a way to extract or otherwise calculate the boundaries of that portion, then we could overlay something (e.g. a gray rectangle) over the barcode and scan it again. Kind of like your suggestion, except it wouldn't involve cropping the image.

**Comment by TheLastProject** [comment]
So it turns out this whole time I could've just wrapped it into a "MultipleBarcodeReader" class provided by ZXING that I just didn't know about.

There's a LOT of parts of Catima that need rewriting, but this turns out to be way easier and less fragile than expected.
