### ISSUE TITLE
Brighten barcode view also increases when card has no barcode

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1479]
Got this email:

> Hi,
>
> When i have the option "brighten barcode view" enabled the screen brightness is also maxed out when showing a card without a barcode, that is not as i think its supposed to be. Either call that options different or only increase screen brightness when in fact a code is shown.
>
> Thanks in advance 

I'm not sure if this is really worth considering a bug. I can imagine there are probably more cases of people wanting to use low brightness generally and also wanting the brightness high when it is just a code for easier showing to a shop assistant.

Not sure if worth renaming too, that's a lot of translations that need changing and most translators translate once and then disappear. And rename to what, even?

**Comment by TheLastProject** [comment]
Responded:

> I've put it in the issue tracker, although I'm not really sure if this is something I want to change: https://github.com/CatimaLoyalty/Android/issues/1479
>
> What's your use case? Why would only increasing the screen brightness when there is a barcode be better for you? Why is the current behaviour making the app less useful to you?

**Comment by TheLastProject** [comment]
2 weeks, no response when I mailed them back. I'm closing this.

**Comment by ukanuk** [comment]
I'd appreciate this change, too (I am not the original emailer). I have seven cards in Catima so far, but only four have a barcode.

> I can imagine there are probably more cases of people wanting to use low brightness generally and also wanting the brightness high when it is just a code for easier showing to a shop assistant.

Yes, this is me.

> What's your use case? Why would only increasing the screen brightness when there is a barcode be better for you? Why is the current behaviour making the app less useful to you? 

For me, Catima unexpected brightens even when a barcode isn't visible, which makes it uncomfortable for me to use. The brightness is necessary for some readers, but I don't like seeing the brightness any more than necessary.

**Comment by ProgramminCat** [comment]
I'd appreciate this too, I currently have brighten screen option turned off and will just manually turn up the screen brightness if it has a barcode, but this feature would be great!
