### ISSUE TITLE
Icon looks wrong on Android 14 beta (SDK 34)

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1510]
![video](https://github.com/CatimaLoyalty/Android/assets/1885159/e3641f62-ab73-4595-84ac-7340d751e2cf)

Really Google? You had to change how icons are rendered **again**? For what purpose?! Sigh. Time to hunt for documentation again.

(Spotted in Google Play Pre-Launch Report)

**Comment by theimpulson** [comment]
@TheLastProject looks like a recommendation icon, not the actual launcher icon.

Ref: [Pixel Launcher on Android 11 Beta 1 can suggest apps, here’s how it works](https://9to5google.com/2020/06/10/pixel-launcher-suggestions-apps-android-11-beta/)

**Comment by TheLastProject** [comment]
Ah, thanks! You're probably right. It makes sense in a way too: the emulator just installed the app and didn't pin it to the home screen.

Really weird this is the first time I see it in the Google Play Pre-Launch Report when this feature was apparently added in Android 11 but mystery solved :)
