### ISSUE TITLE
Manual entering can be confusing for new users

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1511]
![image](https://github.com/CatimaLoyalty/Android/assets/1885159/c5c065f0-34ce-4f7f-8058-8f9c8ce0851c)

They had the following suggestions:

> I would suggest a simple change on that screen: Instead of "Enter ID," simply, "Enter ID Number." That one word would have been enough to tell me I'm not entering the merchant name.
>
> There's one more thing, though. I had to do some exploring to figure out the point of all those barcodes. Seriously. My first reaction, honestly, was, "What do I want these for? Why would I pick a barcode that has nothing to do with me or the merchant?"
>
> The labels identifying those barcodes didn't help, either, unfortunately, from a UI perspective. They actually had me wondering, "Is there something about these labels that's supposed to help me answer that question?"
>
> Well, I explored by tapping one of the barcodes, and I saw it made sense after all. I suppose most users would probably solve it just as I did. But I think you might also want to head off that puzzle in the first place.
>
> I suggest you change that screen's instructions to something like this:
>
> Enter your ID number for this vendor, then tap the barcode below that looks most like the one on your card. It will take you to a screen where the app will edit the barcode to match your ID number, and you can add other information as well. If there is no barcode, tap the "No barcode" button.
> 
> And finally for UI confusion's sake, the button, "There is no barcode" doesn't appear until you type something in the ID field. Why not? That's a small matter, and almost everyone would figure it out instantly. Except -- and here's the funny thing -- if you look at the instructions on the screen, you'll see (on my Pixel 7, anyway) the lines wrap so that the second line says,
> >
> > type below, or "There is no barcode".
>
> I am a professional editor, and from experience I can guarantee someone will switch words there and think you're saying,
> >
> > or type below, "There is no barcode."
>
> And they will actually try typing, "There is no barcode."
> 
> Maybe that wouldn't happen if they knew that line was for an ID number. Still, you could probably head off another potential UI glitch just by making the button look like a button even before they type anything at all. It doesn't have to be an active button, it just needs to look like one.
>
> If you made it "No barcode" instead of "There is no barcode," it would simplify the screen, but that's not a UI issue, just a matter of individual preference.
>
> And then, finally-finally, and less essential by far: I suggest removing the barcode labels. Hardly anyone knows barcode styles even have names like these, so instead of being useful information, they serve as clutter (at best) or confusion (at worst).
>
> I hope that makes sense.

**Comment by TheLastProject** [comment]
I'm seeing a few issues with that, most notably that the "Card ID" is not necessarily a number, sometimes the Card ID can be letters too (although that is more rare).

The button does follow Android styling of inactive, but may need more padding on the sides.

I'm thinking of perhaps introducing the following changes, which allows us to remove the out-of-place button, but I'm not 100% sure on them yet:

1. On the "Scan Barcode" screen, replace the "Select image from gallery" button and "Manually enter ID" button with a [Extended FAB](https://m2.material.io/components/buttons-floating-action-button#extended-fab) button saying something like "Advanced options" to keep these options available but discourage them for non-technical users.
2. When clicking "Advanced options", a Material Alert Dialog pops up with the title "Add a card in a different way" with 3 buttons: "My card has no barcode", "Select barcode manually" and "Use image from gallery"
  1. When clicking "My card has no barcode", a text input field shows up.
  2. When clicking "Select barcode manually" you get to the original manual entering screen, but without the "No barcode" button to simplify it
  3. Use image from gallery is unchanged
3. In the "Select Barcode" screen change the text to "Enter the value of your card and pick the barcode that looks like the one on your card."
4. In the "Edit Card" screen, maybe we need to change something too? Maybe rename "Edit barcode" to "Select barcode" to indicate it'll open the barcode selection screen.

**Comment by obfusk** [comment]
> remove the type labels

Some of them look very much alike. I get that most users won't know the names, but I'm not sure removing them is a good idea. And "show them in a toast on long-press" is not something users might consider trying. Not sure what the best solution is here.

**Comment by obfusk** [comment]
At least if you can see the different type names you might have some clue if you can't tell which one to pick. idk.

I'm not exactly an average Catima user, but removing them seems like a bad idea to me.

The rest of the changes you proposed sound good.

**Comment by TheLastProject** [comment]
I haven't heard anything back from this user so I'm going to assume #1512 resolves this.
