### ISSUE TITLE
Migrate to MaterialDatePicker

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1516]
[MaterialDatePicker looks a lot more modern](https://github.com/material-components/material-components-android/blob/master/docs/components/DatePicker.md), it would be great if the LoyaltyCardEditActivity would use it.

I tried quickly swapping DatePicker for MaterialDatePicker and while that tends to work for dialogs, it didn't want to work in this case. So more research and work is needed.

Tagging as "good first issue" because the scope of this change is very narrow and well-defined and likely needs knowledge of the MaterialDatePicker more than knowledge of Catima. Please note, I am likely unable to help with the initial implementation.

**Comment by Kundai10** [comment]
I would like to work on this issue. Is it still available?

**Comment by obfusk** [comment]
@Kundai10 I was considering looking into this but haven't had a chance to do so yet; AFAIK no one else is currently working on this.

**Comment by Abdullahkhanspn** [comment]
i will do this issue i know how to implement this please assign to me @TheLastProject

**Comment by TheLastProject** [comment]
I think @Kundai10 is already planning to work on this, let's give them some time first :)

**Comment by Abdullahkhanspn** [comment]
Okay after him please assign me this @TheLastProject

**Comment by Kundai10** [comment]
@Abdullahkhanspn you can work on it. I am not working on this issue.

**Comment by Abdullahkhanspn** [comment]
okay i will see

**Comment by Abdullahkhanspn** [comment]
@Kundai10 can you please tell me how to setup the project locally in android studio. Please tell me i am yesterday clone it in my laptop but when i open and run it on android studio its show soo many gradle build error. Please guide me bro

**Comment by Abdullahkhanspn** [comment]
hey @TheLastProject I think you can now assign this issue to me if you want because @Kundai10 is not working on this .And i can Migrate this to the MaterialDatePicker like this sample its looks modern and user friendly.


![MaterialDatePicker Sample](https://github.com/CatimaLoyalty/Android/assets/140059001/9cdfe670-4960-4351-8b01-461a06ac4272)

**Comment by Abdullahkhanspn** [comment]
hey @TheLastProject can you please tell me how to fix this gradle error i have started working on it but its shows me this.

![gradle error please tell how to fix this](https://github.com/CatimaLoyalty/Android/assets/140059001/82904a3f-37e3-43d0-b92d-34fc0ff79a20)

**Comment by TheLastProject** [comment]
Sorry, I don't know. I can build fine myself and so can the GitHub CI, both don't show any such error and I've never seen this error before. I'm sure some StackOverflow thread or Android support community would know the answer to this but I don't have any to point you at either.

(If you ask others for help, I recommend giving them the full error message as the useful info may be anywhere, you're only showing me the first 20 or so percent of it here)

**Comment by Abdullahkhanspn** [comment]
Okay, I understand the error I thinks it's a very simple setting the setting of my android studio was changed. I will fix this soon the code is all good the error is coming from my settings i think. I will Fixed it soon. 
And Thanks for your suggestion.
