### ISSUE TITLE
Group does not update correctly when showing/hiding archived cards if group has 0 non-archived cards

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1525]
How to reproduce:
1. Create group with only archived cards
2. Uncheck "Show archived cards"
3. Notice Catima displays nothing instead of the "This group is empty" text

Or:
1. Create group with only archived cards
2. Check "Show archived cards"
3. Notice Catima still displays "This group is empty" instead of showing the archived cards

**Comment by dinesh-thiyagarajan** [comment]
Hey I can pick up this bug :)

**Comment by TheLastProject** [comment]
Thanks for the offer! I kinda want to first give this one a try myself (which is why I assigned it to myself) because I think I already know where the mistake is. But if I get stuck or something I'll post in this issue :)

"Show archived cards" is under "Display options" by the way, the little eye icon in the top-right of the main screen.
