### ISSUE TITLE
Transliterated app name: how to deal with this

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1539]
We hardcode the Catima spelling as Catima: https://github.com/CatimaLoyalty/Android/blob/5924c8616c4ba2ae6f1c8838e12bd99fbd0f7bd5/app/build.gradle#L35

But users may translate it differently: https://github.com/CatimaLoyalty/Android/blob/0f2f430b7fd2a4fa37288b3a5fb5e104e5a7deea/fastlane/metadata/android/hi-IN/title.txt#L1

The feature graphics generation considers this invalid and uses the English translation: https://github.com/CatimaLoyalty/Android/pull/1538/files

I really don't know what is "normal" in different countries and thus if we should maybe stop hardcoding the way the app is written. Or maybe consider translations in Fastlane to be invalid.

**Comment by Akshayp02** [comment]
Hello @TheLastProject,

I hope this message finds you well. I've been actively involved with the project and have come across an issue that I'd like to help address. The issue in question is labeled as "Dynamic Localization for App Name," and I believe it's an important enhancement that would improve the user experience for non-English speaking users.

Issue Description:

The problem revolves around hardcoding the app name ("Catima") in the build.gradle file, which can lead to translation conflicts and challenges in delivering a localized experience. Users in different countries may prefer to see the app name translated into their native language, and the current setup doesn't allow for this flexibility.

Proposed Solution:

I propose implementing dynamic localization for the app name, allowing it to be translated into different languages. This change would involve creating separate resource files for each supported language and updating the app's code to reference these resources.

Benefits:

Improved user experience for non-English speaking users.
Enhanced accessibility and inclusivity for a wider audience.
Alignment with best practices for app localization.
My Commitment:

I'm enthusiastic about contributing to this project and am willing to take the lead on implementing this enhancement. I have experience with Android app development and localization, and I believe I can make a positive impact on this aspect of the project.

I kindly request your approval to work on this issue and your assistance in assigning it to me. If there are any specific guidelines or preferences you have regarding the implementation or review process, please let me know, and I'll be sure to adhere to them.

**Comment by TheLastProject** [comment]
Did you use ChatGPT to write this? That's a lot of text for "the bug is hardcoding the app_name in build.gradle as you thought it may have been, I can fix it".

If you can fix it, go ahead :)

**Comment by Akshayp02** [comment]
Actually, I'm just explaining the things that are happening with it and providing a viable solution for it😅. Yes, ma'am, I would like to contribute to this problem. Can you assign it to me to explore more.

**Comment by TheLastProject** [comment]
I'm sorry, it sounded like ChatGPT or the way some people at work write tickets :sweat_smile: Good luck and thanks for confirming this is an actual issue for some languages :)

**Comment by Akshayp02** [comment]
No worries mam, 😊 I'll try my best.

**Comment by TheLastProject** [comment]
Reopening because the Fastlane parsing still needs to be fixed.
