### ISSUE TITLE
Android 14

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1549]
Just from quickly scanning the release notes for Android 14:

[Effective on all Android 14 devices *now*](https://developer.android.com/about/versions/14/behavior-changes-all):

- [Grant partial access to photos and videos](https://developer.android.com/about/versions/14/behavior-changes-all#partial-photo-video-access) <- Not sure if relevant, but may be forced to merge #1288 anyway. Needs better research.

[Effective after updating targetSdk](https://developer.android.com/about/versions/14/behavior-changes-14):

- [Restrictions to implicit and pending intents](https://developer.android.com/about/versions/14/behavior-changes-14#safer-intents)
- [Zip path traversal](https://developer.android.com/about/versions/14/behavior-changes-14#zip-path-traversal) <- most likely irrelevant, if it crashes that's probably good anyway

**Comment by Abdullahkhanspn** [comment]
hey @TheLastProject i think i will do this i have developed a new android app recently and i have also makes more then 6+ Android apps . Can you please gave some clue what to do in this , I this Grant partial access to photos and video work i will try in my Android Studio and also update and see the targetSdk . So please tell me what i do in this Android 14 issue and i will work on this .

**Comment by TheLastProject** [comment]
Someone already wrote photo picker support in #1288 but as written there it doesn't access all photos so using it would create a worse user experience which is why I haven't merged it yet. I wrote "needs better research" because we need to research if we can still avoid using the photo picker given it doesn't work properly due to Google designing it stupidly. There is no code task there as far as I can tell, we already have the code we need if Google forces us to make the user experience worse by not letting users select all images, we need to double check if we are being forced to make it worse on Android 14.

**Comment by Abdullahkhanspn** [comment]
yes i know but i will do this later @TheLastProject first i do the migrate materialdatepicker after that i will see what the things was to be replaced in this .

**Comment by Abdullahkhanspn** [comment]
okay @TheLastProject I am currently working on the MaterialDatePicker Migration in the LoyaltyCardEditActivity.

**Comment by theimpulson** [comment]
I don't think this is blocked by upstream anymore, right @TheLastProject?

**Comment by TheLastProject** [comment]
You're right, Robolectric should support Android 14 fully now. Just haven't had the time to test and make sure there are no regressions although I expect 0 issues.
