### ISSUE TITLE
Feature Request: switch to different card with volume keys

### ISSUE THREAD

**Issue by cpy82** [CatimaLoyalty/Android#1553]
Hello,
Would it be possible to integrate the following?

Some kind of self-adjustable timer to automatically switch to the next saved barcode - perhaps only in the favourites area?

Use case: You have a customer card and several discount coupons to scan at the POS. Currently, I mark these as favourites before shopping and then scan them one after the other by manually scrolling through them. It would be nice if these could be scrolled automatically after freely adjustable seconds (milliseconds?), so that you only have to hold the smartphone in front of the barcode scanner.

There should also be something like a start signal. Button? Or even a certain period of time?

**Comment by TheLastProject** [comment]
I've been thinking about this for a bit but I'm thinking there might be a better way that should also solve your use case.

As I understand it you want to be able to keep holding the device in place while multiple barcodes get scanned without trying to press the small "next" button. I think we can actually fix that in another way that also helps users who have issues pressing small UI elements (think of hand tremors for example):

An option in Catima settings under "Accessibility" called "Use volume keys to switch visible card". When enabled, you could press the volume up key while viewing a card to go to the next card and the volume down key to go the the previous card.

Do you think that could solve your issue too?

**Comment by rzuhovski0** [comment]
Hello,

is this still open? I would like to help you implement this.

**Comment by TheLastProject** [comment]
This issue is still open :)
