### ISSUE TITLE
Extreme battery usage when barcode is shown and app is still open 

### ISSUE THREAD

**Issue by Ronaldvr** [CatimaLoyalty/Android#1686]
When I choose a barcode and forget to close the app, the app prohibits the phone from turning off the screen somehow . This for some reason results in high battery and a hot phone

**Comment by TheLastProject** [comment]
I can't reproduce "high battery usage" (beyond what is normal for max brightness screen on) nor can I reproduce "hot phone" but this behavior is intended. It allows you to select a card while in line without worrying about your phone lock kicking in and you having to unlock when it's your turn to scan.

If you don't want this behavior, disable "Keep screen on" and/or "Prevent screen lock" in Settings.
