### ISSUE TITLE
Exclude archived cards in ShortcutHelper

### ISSUE THREAD

**Issue by brezelman** [CatimaLoyalty/Android#1779]
I marked one of my cards as archived, but it's still listed in the app's long press menu as a shortcut. Other cards, which are not archived and therefor have a higher probability of being used, are not listed there.

I think, there's a limited number of shortcuts an app can provide in that menu, right? So I would expect to at least only show active cards there.

**Comment by TheLastProject** [comment]
Makes sense, I definitely agree the list of shortcuts shown in the long-press menu on the app icon in supported launchers should exclude archived cards as you're very unlikely to want to open those quickly.
