### ISSUE TITLE
Highlight archived cards

### ISSUE THREAD

**Issue by wolfkin** [CatimaLoyalty/Android#1805]
I'd like a way to highlight archived cards when viewing all.

My usage is like this. Most of the time I'm scanning temporary barcodes for vouchers like these:

![image](https://github.com/CatimaLoyalty/Android/assets/6678474/d2975790-718c-4be3-bbac-387b06b1af6a)

(These ones have been used already)

I'll end up with 10-12 vouchers. Use them as I want and then archive them to mark them as used. But at the end of the cycle of their usefulness I prune them from my library. The issue is that while the codes do show red when the expiration date has passed. There's no such indication for cards that are simply archived. I'd suggest maybe [a line](https://thenounproject.com/icon/archive-1315071/) or fading the image or whatever.

Here's a mock up of what I mean

Before: 
![before](https://github.com/CatimaLoyalty/Android/assets/6678474/39d9d48a-1a79-41d2-b17e-cb917f0db741)

After:
![after](https://github.com/CatimaLoyalty/Android/assets/6678474/b5069b73-51ef-410e-b350-bd5d5c38fa38)

**Comment by TheLastProject** [comment]
I'm a bit confused about your request. The grey icon in the top left is already a visual indicator that the card is archived, that icon is only shown on archived cards.

**Comment by TheLastProject** [comment]
It's been a week and a half with no response, so I'm closing it. Feel free to reopen if you have more info :)
