### ISSUE TITLE
About screen text can overflow into arrow

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1842]
Noticed in a longer language (edit: I've been told this is Finnish) in the Google Play Pre-launch report

See text below "Lisenssi"

![video](https://github.com/CatimaLoyalty/Android/assets/1885159/6c4aff19-e9e9-4ded-abc2-94e523ac3d7b)

**Comment by vigneshreddy17** [comment]
Hi, can I take a look at this issue?

**Comment by Cetykon** [comment]
I looked at this, and I believe the fix can be solved by dividing the padding for the field into two (start padding, and end padding). Currently testing and will be doing a pull request with changes soon.
