### ISSUE TITLE
can android.hardware.camera use required=false?

### ISSUE THREAD

**Issue by obfusk** [CatimaLoyalty/Android#1907]
It's currently simply set to `true` in `app/src/main/AndroidManifest.xml`:

```xml
    <uses-feature
        android:name="android.hardware.camera"
        android:required="true" />
```

Might be worth seeing if it can be set to `false` w/o anything breaking (low prio) as catima can be used w/o a camera.

Also, that is specifically the *back* camera: https://developer.android.com/guide/topics/manifest/uses-feature-element#feature-list

**Comment by TheLastProject** [comment]
I think the most important part here is to set up some kind of emulator without camera to test if Catima behaves semi-reasonably. I think devices without camera are so niche it's not really necessary to optimize the UI much aside from not crashing (perhaps at best force-auto-open the "More options" menu in the scanner).

I've been trying to figure out which devices this covers but the Google Play Console Device Catalog doesn't seem to allow me to filter in any useful way. The best I can do is some manual math:
All devices on Google Play: 22907 models
All devices with android.hardware.camera: 20340 models
All devices supported by Catima: 18852 models

So there may be up 22907 - 20340 = 2567 device models without camera that Catima could support, given they're all Android 5+ (no way to filter for that).

Most likely this feature is not very useful for most people. But hey, if we can support the few people who would like to transfer their cards to a devices without camera with minimal effort... why not? :)

**Comment by obfusk** [comment]
> Most likely this feature is not very useful for most people. But hey, if we can support the few people who would like to transfer their cards to a devices without camera with minimal effort... why not? :)

The `android.hardware.camera` feature is specifically the *back camera*. Some of those devices could have a front camera only instead of none at all. Maybe someone out there would be happy to organise their cards on a chromebook. Who knows? Seems worth it if it's minimal effort to support those too :)
