### ISSUE TITLE
In case of an error "No barcode was found" prompt the user to manually specify the area of ​​the image to rescan

### ISSUE THREAD

**Issue by Korb** [CatimaLoyalty/Android#1970]
When adding a large number of pre-photographed cards to the application, I found that about one in 15 required cropping before indicating it to the application as a barcode source. I suggest that if there is an error searching for a barcode in an open file, prompt the user to specify a rectangular area of ​​the image to search for the barcode again.

Maybe rotate the image at the same time. But at least frame it.

> Catima 2.30.0 f-droid
> OS version: Funtouch OS 14
> Model: Vivo T1 4G (V2153)
> Hardware version: MP_0.1
> Build number: PD22010F_EX_A_14.2.7.12.W20
> Baseband version: S.HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.88
> Kernel version: 4.19.157-perf+, 1 Wed Jun 5 10:25:33 CST 2024
> Compile time: 5 Jun 2024 05:20:41
> Android security update: 1 June 2024
> Google Play system update: 1 May 2024

**Comment by TheLastProject** [comment]
Huh, wait, cropping is a workaround for #1215? That is... weird.

I mean, cropping shouldn't be necessary, it's at best a workaround for #1215. But given nobody seems to be willing to help fix #1215 this might be a reasonable workaround...

**Comment by Korb** [comment]
> Huh, wait, cropping is a workaround for #1215? That is... weird.

Yes, thanks, before creating my issue, I saw the issue you specified. However, as I understand it, that issue is about an unsupported encoding type. Am I wrong, this is a duplicate, and instead of creating a new issue, I should have continued that one?

**Comment by TheLastProject** [comment]
Oh, #1215 was meant to be an "same data loading from image instead of camera doesn't work as reliably". So I see these kind of as similar :sweat_smile:
