### ISSUE TITLE
The general search results should include all cards of the group whose name matches the search query

### ISSUE THREAD

**Issue by Korb** [CatimaLoyalty/Android#1974]
For example, I am in the global list of cards added to the application. I have a number of pharmacy cards, a `Pharmacies` group has been created for them, but I decide to use the search in order to find a specific one of them. I can't find it because it's added to the app by brand name, not by the entity name I use to search. Having not found what I need, I understand this, and I have a choice: still remaining in text entry mode, enter another version of the name of the pharmacy chain, or simply start typing the `pharm` to select the one I need from the list provided. However, despite the fact that all pharmacy cards have been added to the `Pharmacies` group, I will only see those whose names or comments contain this word. That is, in this case, it would be better for me not to use the search, but to switch to the `Pharmacies` tab and look for the one I need among the thumbnails of the added pharmacies. In my case, it will take a few more seconds, because on average five out of a dozen tab shortcuts are displayed on the screen at the same time, and the desired tab is out of sight.

**Comment by TheLastProject** [comment]
I'm sorry, but I don't understand what you're asking for here.

**Comment by obfusk** [comment]
I'm guessing this is a request for the search to also include cards whose group matches the query string?

**Comment by Korb** [comment]
@obfusk, exactly, thanks for the succinct explanation!

**Comment by TheLastProject** [comment]
Well, that would break filtering if you're in any group (if you'd search Pharmacy while in the Pharmacy group it won't filter anything) so it would need extra logic to filter out the current group. At which point what the search does will become inconsistent based on which group you're currently viewing.

Given swiping to the group you want shouldn't take long (perhaps we can look into if there is a better way to handle a large amount of groups than horizontal scrolling so switching becomes faster) and disabling your search is also just a single tap on the X (or a swipe back), I think I'd much rather prioritize the search feature being simple, consistent and logical. The group names not being searched is what I think most people would expect given the group is a filter on the top of the screen already (so you're choosing the group to search), and thus most users would logically switch groups instead. Thus, making this change would make the search behaviour less logical and consistent.

So I don't think it's a good idea to implement this, I think it's likely to cause more confusion than be helpful, so I'm going to close this with a wontfix.

**Comment by Korb** [comment]
> if you'd search Pharmacy while in the Pharmacy group it won't filter anything

Exactly! That's how it should be! Only cards from this group will be displayed, and nothing else. It’s like entering some analogue of “all” in a general list. What would you expect to see in the Pharmacy group if you were to type Pharmacy into it? You don't expect that, being in the Pharmacy group, when you type the word Pharmacy in the search, you will see something other than Pharmacy in the search results, or not see all the cards in the Pharmacy group?

> so it would need extra logic to filter out the current group. At which point what the search does will become inconsistent based on which group you're currently viewing.

I don’t see the connection between the example you gave and the consequence of the need to do different search logic depending on whether the group _tag_ filter has already been applied to the general list of cards or not. (After all, at the level of functional concepts, groups here are simply a set of tags assigned to cards, with subsequent visualization through predefined filters in the form of tabs.) Simply, now a user administering a card database for several users will have to add to the description of each card the names of the groups in which each card is displayed. And change the descriptions after each change in the groups to which the card is added. Although, this manual synchronization (duplication of entities) could be implemented through search without changing the principle of its operation.

**Comment by obfusk** [comment]
> You don't expect that, being in the Pharmacy group, when you type the word Pharmacy in the search, you will see something other than Pharmacy in the search results, or not see all the cards in the Pharmacy group?

If I have a group named "Books" and I'm looking for a store that actually has "Books" in its name, I would not expect it to show everything in the group instead of just the stores that actually have "Books" in their name.

IMO it might make some sense to also look at group names *only when no group is selected*. But then "what the search does will become inconsistent based on which group you're currently viewing". I agree with Sylvia here that it's probably better to prioritise consistency here.
