### ISSUE TITLE
Swiping to dismiss keyboard also dismisses search

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1977]
> After entering a search query, it may be natural for a user to want to hide the on-screen keyboard to explore the search results. However, when using the hide keyboard gesture (swiping from the right edge to the middle of the screen), along with hiding the keyboard, the search results are also hidden, returning the user to the full list of cards.

> Catima 2.30.0 f-droid
> OS version: Funtouch OS 14
> Model: Vivo T1 4G (V2153)
> Hardware version: MP_0.1
> Build number: PD22010F_EX_A_14.2.7.12.W20
> Baseband version: S.HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.88
> Kernel version: 4.19.157-perf+, 1 Wed Jun 5 10:25:33 CST 2024
> Compile time: 5 Jun 2024 05:20:41
> Android security update: 1 June 2024
> Google Play system update: 1 May 2024

_Originally posted by @Korb in https://github.com/CatimaLoyalty/Android/issues/1498#issuecomment-2209488488_

**Comment by obfusk** [comment]
Is this related to #1962?

**Comment by TheLastProject** [comment]
No, #1962 is: Main screen -> Search -> Choose card -> Press back -> Search filter is gone

This is: Main Screen -> Click search -> Keyboard appears -> Type search query -> Dismiss keyboard by using the "back" swipe gesture from the side of the screen -> Search filter is also deleted
