### ISSUE TITLE
Handle click outside of import process notification

### ISSUE THREAD

**Issue by Korb** [CatimaLoyalty/Android#1980]
Currently, after taping outside the message that an import is in progress, the message itself disappears and the application stops responding; The OS suggests closing it as unresponsive.

I suggest that in case of a tap outside the import progress notification, ask the user whether he wants to interrupt the import or continue it? Similar behavior seems logical to me with the `Back` gesture.

Another option for the application's behavior: in principle, it will not respond to taps on the screen outside the `Cancel` button on the import progress notification.

**Comment by TheLastProject** [comment]
As written in #1978 as well, the real issue that needs fixing is #513.

Given the current implementation has to go, I'm not really interested in adding more features, so blocking cancelling the import/export seems like the most logical quick hacky workaround for now.
