### ISSUE TITLE
Width for 1D barcode

### ISSUE THREAD

**Issue by budda85** [CatimaLoyalty/Android#2058]
Some scanners cannot read wide barcodes or have a fixed focus. This means that the wide barcode is either blurred if you hold the smartphone further away or the barcode is simply too wide. If I change the height of a 2D barcode, the width also changes automatically.
Unfortunately, this does not happen with a 1D barcode. It would be good if you could also change the width of a 1D barcode.

**Comment by TheLastProject** [comment]
Seems like a duplicate of #788 as far as I can tell. Sadly the community contribution to fix this was never finished. Being able to scale width still sounds sensible to me, but there are only so many hours in a day :)
