### ISSUE TITLE
Add Catima to Accrescent

### ISSUE THREAD

**Issue by jmcelroy01** [CatimaLoyalty/Android#2117]
As [Accrescent](https://accrescent.app/) was recently added to the GrapheneOS app store and recommended ([https://discuss.grapheneos.org/d/14303-accrescent-store/17](https://discuss.grapheneos.org/d/14303-accrescent-store/17)) by the project, it would be very cool if Catima were added to Accrescent to increase the number of apps there, encourage google play store alternatives besides F-Droid, and make more people aware of Catima.

**Comment by TheLastProject** [comment]
I refuse for my apps to be added to anything adjacent of the abusive project that is GrapheneOS.

https://www.youtube.com/watch?v=Dx7CZ-2Bajg
https://www.youtube.com/watch?v=4To-F6W1NT0
