### ISSUE TITLE
Add icons to adding a card in a different way

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#2120]
This screen is a lot of text, it'd be nice to have some icons here too to make it easier to scan for users.

![Screenshot_20241020-111526_Trebuchet](https://github.com/user-attachments/assets/833777f7-252b-44b3-bf7b-446c6bcd09ec)

Preferably the icons come from https://fonts.google.com/icons, as that's the standard Android design. Android Studio should show icons from here when you select them but that has not always been super reliable from my experience, so you may have to download from the website.

We also need to think about what icon we'll use for pkpass support, as that is hopefully coming soon.

When adding the icons, please mention in the MR which icons you used and ensure they work with light and dark themes (most of the other icons are fixed to allow that so look at those).

**Comment by caronvincent** [comment]
I would like to work on this issue if it's still up for grabs.

**Comment by TheLastProject** [comment]
Sure, go for it :)
