### ISSUE TITLE
Add Small Window feature

### ISSUE THREAD

**Issue by Korb** [CatimaLoyalty/Android#2177]
The Small Window (aka **picture-in-picture** mode) feature allows you to display a window overlaying other apps and pin it to the edge of the screen as an always-on small label. The label can be freely moved along the side edges of the screen.

![Screenshot_20241115_234212](https://github.com/user-attachments/assets/dddb7806-1eb8-4f8d-9909-e1a7f387ede0)

More details: Android Developers / Develop / Core areas / UI / Guides / [Support multi-window mode](https://developer.android.com/develop/ui/compose/layouts/adaptive/support-multi-window-mode).

**Comment by TheLastProject** [comment]
I don't recognize the screenshot you posted, where does that come from? Is this a feature of some specific launcher?

I'm having issues thinking of a use case especially because many scanners can't deal with small barcodes or non-full-brightness screens. What use case or issue do you have?

**Comment by Korb** [comment]
> I don't recognize the screenshot you posted, where does that come from? Is this a feature of some specific launcher?

I thought it was not a launcher feature, but an OS feature that should be supported by the app.

> I'm having issues thinking of a use case especially because many scanners can't deal with small barcodes or non-full-brightness screens. What use case or issue do you have?

This mode is needed to place the application in parallel with the main application at the moment. In the case of a loyalty card application, the main application in the case of a queue at the checkout could be a notes application with a shopping list, a news application or a messenger. At the moment when it was your turn to pay, you would only need to double-click on the application sticker to expand it to full screen. Without this, you would have to use a list of recently used applications or even a shortcut on the desktop, which on low-power devices would cause the main application screen to be displayed instead of the page of the previously found card. Accordingly, there would be delays for the user and the queue behind him.

Of course, this is one of many cases. All people are different, as are our habits of using smartphones. It is the same with PC applications: some prefer to use only the mouse and the menu (except for the text box), some - panel icons, some - hot keys. Someone uses voice dictation instead of typing on the keyboard. And it seems strange to me when some users put pressure on you in the spirit of "you're using the device/OS functions/app/time in the checkout line incorrectly".

It is difficult for users to predict whether they will use a particular feature when they are not yet accustomed to it. It is like OS interface updates on a desktop or smartphone. Most innovations, no matter how objectively good they are, are initially criticized by users. But then they get used to them, and use them, and they miss them if they are suddenly deprived of them. The same is with PiP.

I would use this feature. You get used to good things quickly, and I quickly got used to this feature, which is currently implemented in almost all Google apps.

**Comment by TheLastProject** [comment]
> I thought it was not a launcher feature, but an OS feature that should be supported by the app.

I know about Picture-in-picture but I can't find the dialog in your screenshot anywhere on my phone (Android 14, LineageOS). So I'm not sure how that dialog is supposed to work and when it is shown.

> This mode is needed to place the application in parallel with the main application at the moment.

You can already use multi-window mode, which is in the top of [the link you sent](https://developer.android.com/develop/ui/compose/layouts/adaptive/support-multi-window-mode).

> At the moment when it was your turn to pay, you would only need to double-click on the application sticker to expand it to full screen. Without this, you would have to use a list of recently used applications or even a shortcut on the desktop, which on low-power devices would cause the main application screen to be displayed instead of the page of the previously found card. Accordingly, there would be delays for the user and the queue behind him.

You can also maximize one screen in multi-window mode pretty easily. And switching back to Catima will just be a double-tap on the "recently used" button or a tap on recently used and a tap on Catima (for those who still use buttons) or a swipe left (for those who use gesture navigation). So it isn't really slower than tapping twice on a small little thing in the corner.

Also, Catima won't switch back to the main screen. If the device goes out of memory Android reloads the applications from the last activity with the known state (it behaves the same as a screen rotation), so even if your device would go out of memory Catima would open to the same card you last opened again.

> It is difficult for users to predict whether they will use a particular feature when they are not yet accustomed to it. It is like OS interface updates on a desktop or smartphone. Most innovations, no matter how objectively good they are, are initially criticized by users. But then they get used to them, and use them, and they miss them if they are suddenly deprived of them. The same is with PiP.

Sure, but it is also important to not overwhelm users, especially adding multiple ways to do the same thing can cause a lot of confusion and increase complexity. The next thing you get is users asking for a setting to disable that. And then you have more settings, making the settings screen more confusing and making it harder for users to find what they need.

This is why I want to *solve problems*, not *add features*. If the way to solve a problem is to add a feature, sure, it can be considered. But right now I'm not really seeing a real problem? We're switching 2 taps (or one swipe) on the menu bar to 2 taps on a small window in the corner and adding the risk some users who are not as used to PiP will be unsure how to get the app back or, even worse, will try to point the way too small preview at the scanner and complain it won't scan.

I'm really having trouble to see a real use case here. sorry. I currently just see more complexity, both in the codebase and for the app usage.
