### ISSUE TITLE
Archive icon not always correctly adapted

### ISSUE THREAD

**Issue by solokot** [CatimaLoyalty/Android#2249]
The archive card icon is not adapted to white background (is only visible when the card is selected).

Catima 2.34.1 F-Droid build
OS: Android 11 MIUI 12.5

![Strip 4](https://github.com/user-attachments/assets/f0cf8d53-f1f2-4a46-a6fe-c2945f73367a)

Attached is a thumbnail file from the backup archive for clarification colors.
>![card_15_icon](https://github.com/user-attachments/assets/be981d64-22c6-4162-ac62-1cae13c1a043)

**Comment by TheLastProject** [comment]
Need to test to confirm but looks like Catima somehow sees that image as one needing a white background instead of a black one.

Seeing your timing, did this change in some version (did it work before) or did you not test this image before?

**Comment by solokot** [comment]
I noticed it earlier. I have now installed version 2.26 from github (selected at random), restored data from a backup. I have exactly the same problem, i.e. the old one.

**Comment by TheLastProject** [comment]
I can confirm this. The issue at hand seems to be that Catima bases this on the "dominant" colour, which for this image is green (even though most the image is white). In a way, this seems vaguely related to #2250.

It seems that using the Palette dominant color is mostly good for choosing the status bar color (with a few edge cases as you named in #2250), but is not good for choosing the icon colour.

It should be noted that the star icon has no problem with this, as it is made of two layers (the image itself, and a second "border" layer). However, doing the same for the archive icon seems to just make it very dark.

Not quite sure yet how to best fix this. Preferably, the icons would always have a two-coloured border so it works on any background but I'm horrible at graphic design :sweat_smile:

**Comment by TheLastProject** [comment]
Got some help and created #2253. Should fix your case. I tested it even with an image of the exact greyscale of the new icons (#D3D3D3) and it remained visible :)

**Comment by solokot** [comment]
Yep! The debug build https://github.com/CatimaLoyalty/Android/pull/2253 solved not only https://github.com/CatimaLoyalty/Android/issues/2249, but https://github.com/CatimaLoyalty/Android/issues/2248 look fine too!

**Comment by TheLastProject** [comment]
That's very strange, as I didn't touch anything related to that (just fixed some small things in the icon layout), but well, let's close that too then, can always reopen if it pops back up :)

**Comment by solokot** [comment]
Then it’s really strange, but now I checked again: I installed https://github.com/CatimaLoyalty/Android/releases/tag/v2.34.1 and https://github.com/CatimaLoyalty/Android/pull/2253 completely clean, restored the data from the same backup - the debug build does not have the problem https://github.com/CatimaLoyalty/Android/issues/2248 of displaying vertical lines.
