### ISSUE TITLE
quick launch shortcut on the lock screen

### ISSUE THREAD

**Issue by OmlineEditor** [CatimaLoyalty/Android#226]
other apps have the option to make a shortcut to launch on the locked screen. This is very convenient for quickly launching the app. see how this is done in other applications, for example: QKSMS, Open Camera, AFWall, Binary Eye. all applications are on f-droid.

**Comment by TheLastProject** [comment]
Could you show me step-by-step how to do that for one of those apps and what Android version you use? I have heard of this before but I think my Android version may be too new (if I'm not misunderstanding).

**Comment by OmlineEditor** [comment]
My Android 9.0 (Havoc-OS v2.9 https://havoc-os.com/)
it's very simple: In the settings there is a menu lock screen. in this menu there is an item shortcuts. in this menu, you can only select two shortcuts on the left and right of the lock screen.

P.S. I can't take a screenshot from the locked screen.

**Comment by TheLastProject** [comment]
Oh, I see what you mean now. I thought Google removed that from Android! Thanks for the info, I'll go figure out why Catima isn't shown in there.

**Comment by TheLastProject** [comment]
Having trouble figuring out what the difference is. Added "help wanted" in case someone knows. Maybe I'll figure it out at some point but web searches and comparing AndroidManifest.xml files aren't helping much.

**Comment by Kethen** [comment]
https://github.com/Havoc-OS/android_frameworks_base/blob/44ea386a8eb0ccfd874dffee02924361a4e67ce8/packages/SystemUI/src/com/android/systemui/tuner/ShortcutPicker.java#L109
https://github.com/Havoc-OS/android_frameworks_base/blob/71c5fcb4f94bb8097d5ca50dd7039abe93337fb4/packages/SystemUI/src/com/android/systemui/tuner/ShortcutPicker.java#L91

It is a bug in havocOS based on 9-11, please tell them that they are not listing apps that does not have shortcuts properly

**Comment by OmlineEditor** [comment]
thanks for the explanation. perhaps the problem will be solved in new versions HavocOS

**Comment by TheLastProject** [comment]
Closing as not our bug

**Comment by OmlineEditor** [comment]
it wasn't a bug, it was a request for new functionality :)

**Comment by benjuade** [comment]
Quick access explained here: https://source.android.com/docs/core/connect/quick-access-wallet

**Comment by TheLastProject** [comment]
> The Quick Access Wallet card provider is the default NFC payment app.

Sadly Catima doesn't do NFC payment, which is why I think we can't opt up for this. But if I'm wrong code would be cool, I tried but didn't progress myself sadly.
