### ISSUE TITLE
Add auto backup

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#23]
<a href="https://github.com/natrius"><img src="https://avatars3.githubusercontent.com/u/7243447?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [natrius](https://github.com/natrius)**
_Friday Apr 27, 2018 at 12:49 GMT_
_Originally opened as https://github.com/brarcher/loyalty-card-locker/issues/238_

----

Add the option to autobackup after a new card is saved.

**Comment by TheLastProject** [comment]
<a href="https://github.com/huste"><img src="https://avatars1.githubusercontent.com/u/9739281?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [huste](https://github.com/huste)**
_Sunday Mar 10, 2019 at 19:20 GMT_

----

In addition, I'd like to create the backup in a specific place, so that my nextcloud sync tool finds the export and uploads it to my cloud...

**Comment by TheLastProject** [comment]
<a href="https://github.com/trymeouteh"><img src="https://avatars3.githubusercontent.com/u/31172274?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [trymeouteh](https://github.com/trymeouteh)**
_Tuesday Sep 17, 2019 at 02:33 GMT_

----

To have auto backup to the cloud or even syncing to the cloud will be handy. If you lose your phone, adding all the cards back into the app can take quite some time to do.

Please add a encrypted auto backup. I would like to suggest using 7z for encryption.

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Tuesday Sep 17, 2019 at 05:51 GMT_

----

I'll probably not work on this feature myself. If someone were interested in contributing it I'd be happy to review the pull request.

As a note, this app does not have the network permission. This is intentional. If someone were to add a backup option, it may have to be done via a second app. Maybe a plugin app that receives card updates or the like. The solution would need to involve not adding the network permission to this app.

As for the format of the backup, as another app would handle the data the format is unimportant (and thus 7z is fine). Support for importing 7z data would need to be added to this app. To be consistent it may also be worth while adding support for exporting to 7z (mentioned in https://github.com/brarcher/loyalty-card-locker/issues/285)

**Comment by TheLastProject** [comment]
<a href="https://github.com/natrius"><img src="https://avatars3.githubusercontent.com/u/7243447?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [natrius](https://github.com/natrius)**
_Tuesday Sep 17, 2019 at 08:30 GMT_

----

No need for network anything. Just add a option like "Auto save when new card is added" and "Choose destination" everything else can be done with nextcloud autoupload for example.

Also, for this feature, there is no encription needed. Just keep the current one and at least let us choose the destination folder, that would be awesome.

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Monday Oct 07, 2019 at 06:33 GMT_

----

Recently I added https://github.com/brarcher/loyalty-card-locker/pull/311, which allows a backup manager on the system to backup and restore the app's data. This should allow a use case such as:

> If you lose your phone, adding all the cards back into the app can take quite some time to do.

to be taken care of. Do you agree? Given this, is it necessary to have a separate automatic backup mechanism directly in the app?

**Comment by TheLastProject** [comment]
<a href="https://github.com/huste"><img src="https://avatars1.githubusercontent.com/u/9739281?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [huste](https://github.com/huste)**
_Monday Oct 07, 2019 at 16:04 GMT_

----

If somebody can recommend a stable, preferably open source, backup solution not requiring root, that creates complete backups locally on the SD card which I can then sync to my nextcloud instance, maybe that's enough.

Then again, an auto-export after editing cards to a prefefined directory, keeping exports from the last say 6 months, could be a nice feature independent of external backup solutions.

EDIT: added the part about not requiring root...

**Comment by TheLastProject** [comment]
<a href="https://github.com/natrius"><img src="https://avatars3.githubusercontent.com/u/7243447?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [natrius](https://github.com/natrius)**
_Monday Oct 07, 2019 at 19:48 GMT_

----

I would just need an option to choose the backup location, as it now just safes into sd-card root (i think). ideall an autobackup after a new card is added. 

I was asking this because i'm not using any backup-solution right now because linageos has none builtin. Titanium is not available for me (and i don't like it that much), but there is oandbackup available in the f-droid store, maybe thats worth a try for you at least @huste 

Still, appreciate your effort @brarcher thanks. When something like that is not added, i guess i can't change it on my own :D

**Comment by TheLastProject** [comment]
<a href="https://github.com/huste"><img src="https://avatars1.githubusercontent.com/u/9739281?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [huste](https://github.com/huste)**
_Tuesday Oct 08, 2019 at 19:59 GMT_

----

@natrius: No, oandbackup is nothing fo me, my device is not rootable.

**Comment by TheLastProject** [comment]
<a href="https://github.com/natrius"><img src="https://avatars3.githubusercontent.com/u/7243447?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [natrius](https://github.com/natrius)**
_Wednesday Oct 09, 2019 at 07:40 GMT_

----

Oh, missed that, i'm sorry. I'm not aware of such an possibility. 

Seems like you have to: 

1. Open the app
2. press the backup button
3. close the app
4. open the filebrowser
5. move the file to the autoupload folder from nextcloud manually
6. let nextcloud autoupload the file

Thats the way i'm doing it right now, because unfortunately its not possible to choose the backup locatio :(

**Comment by TheLastProject** [comment]
<a href="https://github.com/huste"><img src="https://avatars1.githubusercontent.com/u/9739281?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [huste](https://github.com/huste)**
_Wednesday Oct 09, 2019 at 11:48 GMT_

----

@natrius: yes, that's what I do right now If I don't forget. So the simplest solution would be to reqeust external write permission and if granted an option for auto-save after editing. I vote for keeping this issue open.

**Comment by TheLastProject** [comment]
<a href="https://github.com/natrius"><img src="https://avatars3.githubusercontent.com/u/7243447?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [natrius](https://github.com/natrius)**
_Thursday Oct 10, 2019 at 11:18 GMT_

----

@brarcher 

Could you change the default-safe folder from sd-card root to a "backup_loyaltycard" subfolder at least? This would be the easiest solution for now, because we could set up autoupload for this folder and from then on just press "Backup" in the app itself, if the other changes are to difficult to make.

**Comment by trymeouteh** [comment]
Please add auto backups which will be done after add, editing or deleting a card into an encrypted backup folder. I would recommend using something like 7z or gz which are archived file types that support password protection.

**Comment by TheLastProject** [comment]
I wonder if we should maybe just... change everything up in general. Like, do it more WhatsApp style:
1. Automatically make a local backup (SD Card -> Catima -> Catima.csv)
2. When starting the app with no cards and groups, offer to import this automatic backup
3. Allow the user to disable the automatic backup

That way, if people change phones but keep their SD card or uninstall the app or something they won't lose everything. And more advanced users could already add this directory to their Nextcloud/Dropbox sync directories or something.

I am wondering if we want to offer changing the automatic backup location because if the user does change it we can't detect the file for automatic importing either...

**Comment by natrius** [comment]
My take on that, on startup:

- 1. let the user decide if he wants to backup at all (if no: abort, if yes: ii)
- 2. let the user choose the location of the backup (but set default-location)
- 3. detect if backup is at the chosen location (if no: step v, if yes: step iv )
- 4. ask if the found backup should be imported
- 5. let the user choose how often it should be backupped (every opening of the app, after adding a new card, after changing a card) or fix it with "after changing a card" because that would basically cover the new card and everything is safed) and probably less hassle to program

Not a lot to change when activating after the initial launch, i guess.

**Comment by trymeouteh** [comment]
As long as the backup can be done when an card is added, edited or deleted I am happy. That way I can use Syncthing to make a copy of the backup on another device.

**Comment by TheLastProject** [comment]
This is partially possible already as I understand it. Because Catima does not opt out of Android's backup framework, using Seedvault should also backup Catima's data

**Comment by trymeouteh** [comment]
All that is needed to implement this is the following settings,

- Choose Directory to store automatic backups (The directory to store automatic backups)
- Automatic Backup Password (The password that it will set on the ZIP backup)
- Enable Automatic Backups (Toggle switch on weather to have automatic backups)

Automatic backups will occur when you edit a card, delete a card, or create a new card.

For those who like to buy many gift cards with crypto from Bitrefill and Coincards, this automatic backup will ensure no loss of data when one uses Syncthing alongside with automatic backups enabled.

**Comment by TheLastProject** [comment]
I am pretty sure it is not that simple because Android apps aren't supposed to just write to storage anymore.

In fact we may need MANAGE_STORAGE permission to do this which may get us rejected from Google Play. See https://developer.android.com/training/data-storage/manage-all-files#all-files-access-google-play.

So that would require multiple app flavors, one for F-Droid that has this feature and one for Google Play that doesn't.

So that is going down a road of absolute hell that I do not want to go down.

We are likely better off seeing if something like Nextcloud lets us include a library or intent or something to ask it to save some data.

So no, this is not easy at all. Patches welcome from whoever wants to spend time figuring this out, which isn't me because I don't need this feature myself and I want to focus on features I would use myself.

**Comment by TheLastProject** [comment]
I am closing this.

Catima already opts into Android's backup framework for backups, so auto-backup exist. And Google is making auto exporting to a public file increasingly difficult.

For multi-device, #791 is a much better solution.

**Comment by Terrance** [comment]
Are permissions still the blocker here?

As I understand it, no storage permissions are required to use a "well-known" directory like `/Downloads`, or to use SAF and let the user pick a directory you'll have access to, in order to read and write your own app's files (visibility of other apps' files requires the explicit storage permissions).

For context, I'm looking for an automated on-device backup solution rather than multi-device.  I set any apps with backup options to export their data to `/Backups/<app>` on the internal storage (if they allow choosing the location; a few just use `/Downloads/<app>`), version/rotate the backups if the app writes to the same file each time, and then sync `/Backups` and parts of `/Downloads` to a PC to keep an external copy.  I don't really want to be dependent on Google device backups (which are pretty limited in how you restore them), nor manually running ADB backups.

E: Apologies, just spotted #1464 where this continued.
