### ISSUE TITLE
Belarusian Ruble possible issue

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#429]
Got this in my email:

Hello I live in the Republic of Belarus When you need to choose a currency for a card, the application offers the following designations for the Belarusian ruble BYB BYR or Br And it turns out that BYB and BYR are outdated designations of the national currency, they were used before and before, respectively, each Br is about the abbreviation of the word ruble in English. As a result, the ISO BYN code is missing. Perhaps this is not critical for such an application. And if it is critical, then I hope that you will fix it 

Original message:
Здравствуйте  Я живу в Республике Беларусь   Когда нужно выбрать валюту для карты приложение предлагаeт для белорусского рубля следующие обозначения   BYB  BYR  или Br  И  получается  что BYB и BYR   это устаревшие обозначения национальной валюты  они использовались до   и до   соответственно каждая  Br   это про сокращение слова  рубль  по английски   В  итоге код ISO     BYN   отсутствует  Возможно это некритично для такого приложения  А если критично  то надеюсь  что вы исправите

It sounds like we are displaying outdated currency options too that we shouldn't

**Comment by IllusiveMan196** [comment]
Seems like change was not that recent: ConvertPad by MathPad on GPlay uses BYN designation and it was last updated on 2020.07.08
Yeah, quick Wiki search confirms this as BYN was introduced in 2016, Br is its "symbol" if to believe that same article.
