### ISSUE TITLE
Pkpass file support

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#48]
<a href="https://github.com/jeroen7s"><img src="https://avatars0.githubusercontent.com/u/10954827?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jeroen7s](https://github.com/jeroen7s)**
_Saturday Sep 07, 2019 at 14:40 GMT_
_Originally opened as https://github.com/brarcher/loyalty-card-locker/issues/309_

----

.pkpass is a file format specifically for "tickets, passes, coupons or member cards, and also student IDs, loyalty cards"

https://www.file-extension.info/format/pkpass

It's supported by some other popular apps like StoCard, and used by airlines

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Thursday Sep 12, 2019 at 06:18 GMT_

----

This app uses the ZXing library for barcode support. Looking at the list of formats supported by that library:

https://github.com/zxing/zxing/#supported-formats

it does not appear that it is supported. If that project supported the format, there may be a case for adding support for it here also. That project is in maintenance mode, though, so I'm not sure how likely it is.

**Comment by TheLastProject** [comment]
<a href="https://github.com/jeroen7s"><img src="https://avatars0.githubusercontent.com/u/10954827?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeroen7s](https://github.com/jeroen7s)**
_Saturday Sep 14, 2019 at 15:42 GMT_

----

Pkpass is not directly a barcode format, but a file format containing info card-ids/private keys instead of a numeric barcode, which would make it outside of the scope of the zxing project

**Comment by TheLastProject** [comment]
<a href="https://github.com/brarcher"><img src="https://avatars1.githubusercontent.com/u/5264535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brarcher](https://github.com/brarcher)**
_Monday Sep 16, 2019 at 04:17 GMT_

----

Ah. If that is the case, what specifically is the ask? Is it to display the barcode data differently if it is pkpass?

**Comment by TheLastProject** [comment]
<a href="https://github.com/TheLastProject"><img src="https://avatars1.githubusercontent.com/u/1885159?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TheLastProject](https://github.com/TheLastProject)**
_Sunday Dec 08, 2019 at 23:22 GMT_

----

I've done a bit of research on this. Pkpass is commonly used for tickets (think plane tickets or CCC). They're actually zip files containing a pass.json file together with some other to us unimportant stuff.

Taking as example https://github.com/keefmoon/Passbook-Example-Code/blob/master/Pass-Example-Generic/Pass-Example-Generic.pkpass

The pass.json file looks as follows:
```
{
  "passTypeIdentifier" : "pass.keefmoon.example-generic",
  "formatVersion" : 1,
  "teamIdentifier" : "YAXJZJ267E",
  "organizationName" : "Passbook Example Company",
  "serialNumber" : "0000001",
  "description" : "Staff Pass for Employee Number 001",
  "associatedStoreIdentifiers" : [
  	 284971959
  ],
  "locations" : [
  	{"latitude" : 51.50506, "longitude" : -0.01960, "relevantText" : "Company Offices" }
  ],
  "foregroundColor" : "rgb(255, 255, 255)",
  "backgroundColor" : "rgb(90, 90, 90)",
  "labelColor" : "rgb(255, 255, 255)",
  "logoText" : "Company Staff ID",
  "barcode" : {
  		"format" : "PKBarcodeFormatQR",
  		"message" : "0000001",
  		"messageEncoding" : "iso-8859-1",
  		"altText" : "Staff ID 0000001"
   },
  "generic" : {
  	"headerFields" : [
  		{
  			"key" : "staffNumber",
        	"label" : "Staff Number",
        	"value" : "001"
  		}
  	],
    "primaryFields" : [
      {
        "key" : "staffName",
        "label" : "Name",
        "value" : "Peter Brooke"
      }
    ],
    "secondaryFields" : [
      {
        "key" : "telephoneExt",
        "label" : "Extension",
        "value" : "9779"
      },
      {
        "key" : "jobTitle",
        "label" : "Job Title",
        "value" : "Chief Pass Creator"
      }
    ],
    "auxiliaryFields" : [
      {
        "key" : "expiryDate",
        "dateStyle" : "PKDateStyleShort",
        "label" : "Expiry Date",
        "value" : "2013-12-31T00:00-23:59"
      }
    ],
    "backFields" : [
      {
        "key" : "managersName",
        "label" : "Manager's Name",
        "value" : "Paul Bailey"
      },
      {
        "key" : "managersExt",
        "label" : "Manager's Extension",
        "value" : "9673"
      }
    ]
  }
}
``` 

While containing a lot more info than a loyalty card, we could most likely just use the description as name and the info in the barcode JSON field to generate the barcode. And maybe somehow put some of the other info in notes after supporting multiline notes first.

So, supporting this would be:
1. Unzip .pkpass file
2. Parse relevant info from pass.json
3. Maybe put some stuff in notes
4. Discard the rest(?)

Actually not super hard. I think it makes sense to support, although probably only in a basic form. There are other apps like PassAndroid which support this format fully and are better suited for the more complex cases.

**Comment by TheLastProject** [comment]
<a href="https://github.com/TheLastProject"><img src="https://avatars1.githubusercontent.com/u/1885159?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TheLastProject](https://github.com/TheLastProject)**
_Monday Dec 09, 2019 at 16:18 GMT_

----

I started with this in #327.

@jeroen7s As you requested this feature, is there any way you could possibly supply me with some pkpass files and screenshots of how they look like in other apps, if you have any you are willing to share? That will help me ensure the best possible result as I know better what to work towards.

**Comment by TheLastProject** [comment]
<a href="https://github.com/jeroen7s"><img src="https://avatars0.githubusercontent.com/u/10954827?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeroen7s](https://github.com/jeroen7s)**
_Monday Dec 09, 2019 at 22:16 GMT_

----

Thanks for working on this, much appreciated. Found an old plane ticket in my Signal conversations you can use. 
Here's the File: https://intuxikated.stackstorage.com/s/LbC7LhgNnvF6CPzz
And a screenshot of how it looks in the "StoCard" app on the play store:
![signal-2019-09-07-161903](https://user-images.githubusercontent.com/10954827/70477532-f5592000-1ad0-11ea-8a3a-c31bd4b81cf4.jpg)

P.s. I wasn't aware there was already an open source app for this, couldn't find "PassBook" at the time, though having it inside the same app as my loyalty cards would be really nice :)

**Comment by TheLastProject** [comment]
<a href="https://github.com/TheLastProject"><img src="https://avatars1.githubusercontent.com/u/1885159?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TheLastProject](https://github.com/TheLastProject)**
_Wednesday Dec 11, 2019 at 13:35 GMT_

----

Would it be acceptable if I add your flight ticket as a test case? I assume you're not worried about privacy risks because you already posted it on a public bugtracker, but I'd like to make sure just in case.

**Comment by TheLastProject** [comment]
<a href="https://github.com/TheLastProject"><img src="https://avatars1.githubusercontent.com/u/1885159?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TheLastProject](https://github.com/TheLastProject)**
_Wednesday Dec 11, 2019 at 13:45 GMT_

----

On an unrelated note, I absolutely love how the first in-the-wild card I get sent to test with violates the spec every so slightly (incorrect colour code format). Good job, Eurowings!

**Comment by TheLastProject** [comment]
<a href="https://github.com/jeroen7s"><img src="https://avatars0.githubusercontent.com/u/10954827?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeroen7s](https://github.com/jeroen7s)**
_Wednesday Dec 11, 2019 at 13:55 GMT_

----

You can use it for a test-case, however i'd prefer it if you blank out my name tho :D, aside from that you can use it.

**Comment by TheLastProject** [comment]
<a href="https://github.com/TheLastProject"><img src="https://avatars1.githubusercontent.com/u/1885159?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TheLastProject](https://github.com/TheLastProject)**
_Saturday Dec 14, 2019 at 19:59 GMT_

----

Just sharing some progress. Still quite a lot of work left, especially because of the whole i18n system.

![photo_2019-12-14_20-58-59](https://user-images.githubusercontent.com/1885159/70853890-91f63600-1eb4-11ea-887e-8d4ad473c475.jpg)

**Comment by TheLastProject** [comment]
<a href="https://github.com/jeroen7s"><img src="https://avatars0.githubusercontent.com/u/10954827?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeroen7s](https://github.com/jeroen7s)**
_Monday Dec 16, 2019 at 11:28 GMT_

----

Looks like a great start.
Do you really need the i18n tho? 
I think you could add it without translations as a first step and then add translations later?

**Comment by TheLastProject** [comment]
<a href="https://github.com/TheLastProject"><img src="https://avatars1.githubusercontent.com/u/1885159?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TheLastProject](https://github.com/TheLastProject)**
_Monday Dec 16, 2019 at 11:29 GMT_

----

Basic i18n is already working, see pull request :)

**Comment by TheLastProject** [comment]
<a href="https://github.com/jeroen7s"><img src="https://avatars0.githubusercontent.com/u/10954827?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeroen7s](https://github.com/jeroen7s)**
_Monday Dec 16, 2019 at 11:30 GMT_

----

cool, nice work :+1:

**Comment by TheLastProject** [comment]
<a href="https://github.com/devurandom"><img src="https://avatars2.githubusercontent.com/u/63082?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [devurandom](https://github.com/devurandom)**
_Sunday Feb 02, 2020 at 08:36 GMT_

----

Have a look at https://github.com/ligi/PassAndroid, maybe you can borrow / share some code.

**Comment by TheLastProject** [comment]
Okay so... looking back at my code now... wow it was not maintainable. I am very glad @brarcher never merged it back in the days.

Basically, this needs a complete rewrite. From scratch.

While https://github.com/TheLastProject/Catima/pull/69 can be used as reference, https://github.com/ligi/PassAndroid should be taken as reference much more.

So, it anyone wants to rewrite this (because I still think it is welcome in Catima):
1. Make a new database table for this, don't try to shoehorn it into the `LoyaltyCardDbIds` table like I did. The format is just way too different. At most, create an entry in `LoyaltyCardDbIds` for the basics (so it can be nicely integrated in the rest of the app) with the `LoyaltyCardDbIds.ID` field being refered to in your `PkPass` table.
2. See where to go from there.

I'm sorry for dropping this after all this time, but PassAndroid is a very good app and my previous implementation was just not maintainable. I am willing to help anyone who wants to take this up though!

**Comment by Altonss** [comment]
> I'm sorry for dropping this after all this time, but PassAndroid is a very good app and my previous implementation was just not maintainable. I am willing to help anyone who wants to take this up though!

I recently discovered https://apps.kde.org/fr/itinerary/ which seems to work very fine also for tickets (train/plane...) :)

**Comment by e-t-l** [comment]
> > I'm sorry for dropping this after all this time, but PassAndroid is a very good app and my previous implementation was just not maintainable. I am willing to help anyone who wants to take this up though!
> 
> I recently discovered https://apps.kde.org/fr/itinerary/ which seems to work very fine also for tickets (train/plane...) :)

Does KDE Itinerary also do Catima stuff like loyalty cards, gift cards, etc? It would be nice to have one app that handles EVERYTHING involving a bar/QR code...

**Comment by Tragen** [comment]
I love Catima when I first tested it but then I realized it cannot import pkpass.
Since 3 years it's not possible when I read the issues. What's so complicated?
Everything is described in the first comments.

    Unzip .pkpass file
    Parse relevant info from pass.json
    Maybe put some stuff in notes
    Discard the rest(?)

This could be done in a few hours.
I program in C# so I'm not much help with Java.
How can we get this integrated fast? I'm willing so support this with money.

**Comment by TheLastProject** [comment]
> Since 3 years it's not possible when I read the issues. What's so complicated?

The worst complexity is the internationalisation part I suppose. But primarily, the issue is that Catima is a side project and I have a fulltime job and I want to also have time left to spend on other things in my life :)

A lot has changed in Catima since I last put time into this feature though, so it may be easier or harder now, no clue.

> This could be done in a few hours.

Given I tried this before (as mentioned in https://github.com/CatimaLoyalty/Android/issues/48#issuecomment-770450592) I very much doubt it's that simple. Adding a feature in a maintainable way and ensuring stability in a wide range of conditions tends to take a fair share of time too.

(Also, assuming every open issue is "just a few hours" that's still over 100 hours of work. Everyone always considers their own feature most important, so someone is going to be upset no matter what I prioritized and I learned to just prioritize for my own needs)

> How can we get this integrated fast?

There is probably no way to get this integrated fast because I still have a huge to-do list (see all the open Pull Requests, it'd be rude to ignore those who already submitted code) and I kinda burned myself out over Hacktoberfest (I was spending pretty much all my spare time every single day on Catima during it).

The fastest way is probably for someone else to work on this, but I have seen that recently a lot of people are interested in this feature again (I haven't heard any request for this feature in years, it is mostly the last few weeks after Catima got mentioned in C't so it mostly seems to be a popular feature in Germany) so I may pick it up after I've finally gotten to dealing with the currently open pull requests but that'll take a while still.

**Comment by Tycho-S** [comment]
It would be great to have this.. Pkpass is pretty much an industry standard now, and because Android doesn't have a competing standard, I see companies gravitating more towards it. Airline tickets, event tickets etc.

Right now I use StoCard but it's a horrible datamining app, if Catima could do it that would be so great :)

**Comment by Korb** [comment]
For the sake of completeness, it is worth mentioning that this standard was developed with the support of Apple Inc., and the main documentation is located at https://developer.apple.com/documentation/passkit_apple_pay_and_wallet/pkpass

**Comment by TheLastProject** [comment]
I'm trying to take another stab at this in my spare time. I'm having some trouble hunting down good test cases though. So if you have any .pkpass files, especially ones with localization, that you're okay with sharing that would be great. It would be even greater if I'd be allowed to include your .pkpass files in the Catima git repository as unit tests. Feel free to censor some parts (but please do tell me what you censored so I know the manifest correctly won't match and what to look at if things behave weird).

If you have some passes you're willing to share with me but not post publicly, feel free to email the email on my GitHub profile :) Thanks!

**Comment by TheLastProject** [comment]
Hey all, I think I got something that works well enough. I put up a debug build on https://github.com/CatimaLoyalty/Android/pull/2038#issuecomment-2518023687. If anyone has time to check, please try it and report if you run into any new issues. Depending on the severity, I might fix them before doing a new release or delay the fix for the next release. Thank you!

**Comment by Tycho-S** [comment]
Not working for me, sorry. 

When I open a file from the system file manager (and say open in catima) the app crashes. It asked me to clear cache the second time because "the app has a bug" - I think this was a system dialog, not from catima.

When I press the + and then say "more options" and choose the pkpass from there, it doesn't actually do anything. It doesn't import it.

Please contact me directly for more info as I'm reluctant to share the pkpass file or debug log here in the public topic which might contain parts of the ticket :)

**Comment by TheLastProject** [comment]
> Not working for me, sorry.
> 
> When I open a file from the system file manager (and say open in catima) the app crashes. It asked me to clear cache the second time because "the app has a bug" - I think this was a system dialog, not from catima. But even after doing so it didn't work.
> 
> When I press the + and then say "more options" and choose the pkpass from there, it doesn't actually do anything. It doesn't import it. But the app doesn't crash.
> 
> Please contact me directly for more info as I'm reluctant to share the pkpass file or debug log here in the public topic which might contain parts of the ticket :)

Are you using the newest build on https://github.com/CatimaLoyalty/Android/pull/2038#issuecomment-2521260653? I updated it with some fixes after posting the initial link and several people reported those fixes working for them.

I also don't know how to contact you directly, your GitHub profile shows no contact options. So please contact me instead and send me the file so I can check, check my GitHub profile for an email and link to my website with more contact options :)

**Comment by TheLastProject** [comment]
> P.S. Why you don't release debug builds using GitHub pre-release tag? It would be better for us to install

@AT181903 I don't want to spam the release tags and keep bumping the version number, I also don't want to spread this beyond a few testers, it's a quick debug build, not a release in any way :)

**Comment by Tycho-S** [comment]
I did use the one at the end of that thread, yes. And I only downloaded and installed it tonight. I only have one file right now, maybe there's some weird edge case with it.

I thought there would be a direct message thing in GitHub or something :) I don't use GitHub that often. I'm not a developer. I'll contact you tomorrow about this!

________________________________
