### ISSUE TITLE
Starred card disappeared after an update to 2.7.0

### ISSUE THREAD

**Issue by iRomanyshyn** [CatimaLoyalty/Android#481]
Hi! It looks like one of my cards become inaccessible after update to 2.7.0. That card was marked with star and I think there is the problem. And now it was disappeared from the list. I have the backup, but want to know if it can happen again.

**Comment by TheLastProject** [comment]
Thanks for your report! Someone pinged me about this last night, I made a mistake with the migration code and fixed it in 9f0b7604cbf205db4792dca3a1714ced9e0e91ac.

Your card does still exist, but Catima fails to show it, as I missed migrating the very first card to the new search code.

When you update to Catima 2.7.3, the missing card will reappear in the main screen automatically.

From how I see it you have the following options:
1. If you're on F-Droid, wait until 2.7.3 is out if the card is not super important (but sadly this will likely take some days)
2. Create a widget for the card you can't reach from the main screen at the moment to use it from there until 2.7.3 is out.
3. If you're using F-Droid: Make an export of your data, uninstall Catima and install 2.6.1 from F-Droid. Wait with updating until 2.7.3 has reached F-Droid

Sorry again for my mistake, I missed this while testing :(

**Comment by TheLastProject** [comment]
Oh yeah, backup doesn't use the database migration logic, I forgot. That indeed will work yeah.
