### ISSUE TITLE
Respond to image being shared to Catima

### ISSUE THREAD

**Issue by Kalytis** [CatimaLoyalty/Android#614]
Hello,

"QR and Barcode scanner" app on F-Droid gives the possibility to scan a QR or a barcode via the image sharing infobox, or by selecting an image (long-press). It would be super useful to implement this, to quickly add QR codes received by e-mail, or on websites.

Thanks by advance !

**Comment by TheLastProject** [comment]
Huh, I thought there was already an issue for this. But indeed, being able to share to Catima would be a nice feature, it could reuse a lot of the code from the choose image from gallery button.

**Comment by Kalytis** [comment]
My apologies if there was an issue for this, I didn't see it.

Thanks for your hard work !!

**Comment by Kalytis** [comment]
By the way, not sure if this would deserve an issue of its own : do you think there's a mere possibility to implement NFC support on cards ? It would be amazing to put my transport pass on this app and validate it with my mobile, or pay with a credit card...

**Comment by TheLastProject** [comment]
> My apologies if there was an issue for this, I didn't see it.

Nope, I thought there was one but I seemed to be wrong :)

> do you think there's a mere possibility to implement NFC support on cards ?

Sadly not possible, see #166.

**Comment by Pinkolik** [comment]
Hello!
I'd like to give it a try. Can you assign this to me please?

**Comment by TheLastProject** [comment]
Sure, go ahead :)
