### ISSUE TITLE
(Optionally) hide name over logo

### ISSUE THREAD

**Issue by OmlineEditor** [CatimaLoyalty/Android#620]
for beauty, you need to move the name of the card below the logo. now it looks ugly because of the overlay.

![1](https://user-images.githubusercontent.com/13348933/143725367-d96128a7-747b-4f34-9373-31c10e482d62.jpg)

**Comment by TheLastProject** [comment]
Sorry, but I am not planning to move it like that as it would waste important space.

The custom image already gets a darkened overlay to ensure enough contrast and the text will look fine and help for a lot of custom images.

**Comment by OmlineEditor** [comment]
if you will not be moved, then make the setting to turn off the text on the logo completely if there is a logo available.

**Comment by TheLastProject** [comment]
Instead of a setting, I could maybe toggle it for when you tap the image on top. Worth experimenting.

**Comment by inifnite** [comment]
I would like to work on it.

**Comment by OmlineEditor** [comment]
> I would like to work on it. New to open source.

no problem, make changes, later if everything works open the "Pull requests". your code will then be added to the main branch

**Comment by TheLastProject** [comment]
I mean I'm still not sure if I'll merge a feature like this, because it really only fixes something that's more of a personal taste than a real issue and the vast vast majority of people don't even set a custom header image, but you're free to experiment with it. If you want to have a higher change of your code being merged choosing another issue might be better.

**Comment by OmlineEditor** [comment]
> I mean I'm still not sure if I'll merge a feature like this, because it really only fixes something that's more of a personal taste than a real issue and the vast vast majority of people don't even set a custom header image, but you're free to experiment with it. If you want to have a higher change of your code being merged choosing another issue might be better.

if a person is a beginner and has little experience, it is better to start with a simple task like this

**Comment by inifnite** [comment]
I will start working on it just for the sake of experimenting and see how things go.
