### ISSUE TITLE
[Android 5] Rotate icon in icon edit mode is cropped

### ISSUE THREAD

**Issue by Altonss** [CatimaLoyalty/Android#636]
![image](https://user-images.githubusercontent.com/66519591/143935455-ed67873a-1586-4e21-9752-adde505a780b.png)
System information:

    Android 5.0.1
    Device: Samsung Galaxy Core Prime

**Comment by TheLastProject** [comment]
I can confirm this issue on Android 5 (it works well on newer Android version).

Please report this issue to [uCrop](https://github.com/Yalantis/uCrop), as we just use that library as-is and haven't made any changes that could cause this.

**Comment by Altonss** [comment]
> Please report this issue to [uCrop](https://github.com/Yalantis/uCrop), as we just use that library as-is and haven't made any changes that could cause this.

Sadly I don't think that the used library is still actively developed. I would need to read more in-depth this thread https://github.com/Yalantis/uCrop/issues/715 but the last commit is from August 2020.

**Comment by Altonss** [comment]
The issue will probably fixed soon, see the WIP here: https://github.com/Yalantis/uCrop/issues/794#issuecomment-1018395317 :fireworks:

**Comment by Altonss** [comment]
The new version 2.2.8 has been released :fireworks:
