### ISSUE TITLE
Max font size selector is looping (from min directly to max)

### ISSUE THREAD

**Issue by Altonss** [CatimaLoyalty/Android#637]
The font size selector is looping (from min directly to max). When I arrive down to 50%, and I continue to scroll, I continue to 200%. This is a bit a weird behavior. Shouldn't it be better to just have to separate ends at 50 end 200 on each side?

System information:
- Android 5.0.1
- Device: Samsung Galaxy Core Prime

**Comment by TheLastProject** [comment]
I agree it would make more sense to not loop. I use [NumberPickerPreference](https://github.com/invissvenska/NumberPickerPreference) to implement this number picker, which does not currently seem to have such an option.

I have created https://github.com/invissvenska/NumberPickerPreference/issues/15 to ask for this feature.
