### ISSUE TITLE
Scrolling group list may trigger group list swipe

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#699]
Obviously, a group switch shouldn't occur when moving the group list in the main activity to see what groups there are. The group switching listener is probably on the wrong UI level.

https://user-images.githubusercontent.com/1885159/147373901-aa75cdf9-5440-463f-b080-f0688df1fce2.mp4

**Comment by Altonss** [comment]
I have a similar issue, when scrolling up and down in the list of cards (in a tab), sometimes this triggers a tab change. I don't know if it's related but it might be some sensibility issue...idk

**Comment by TheLastProject** [comment]
No, that's another issue. The swiping thing shouldn't respond when you're moving through the group list, your sensitivity thing, well, feel free to make a MR to suggest other values: https://github.com/TheLastProject/Catima/blob/eb38d0a8aa811f420d5717d16802a602d4feae5f/app/src/main/java/protect/card_locker/MainActivity.java#L605-L650

**Comment by TheLastProject** [comment]
This is "fixed" in #1296 by removing the group swipe.
