### ISSUE TITLE
Transparency on long-press

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#706]
Currently, long-pressing a card to select makes the background fully black or white. This makes it harder to recognise the card without having to read the text. It would be good if we could have some transparency again.

So this is what we don't want:
![photo_2022-01-01_22-52-19](https://user-images.githubusercontent.com/1885159/147860904-8fcd0466-3b31-47bb-8b60-c1897d79d4fe.jpg)

**Comment by SamarthAsthan** [comment]
Hey @TheLastProject can i work on this?

**Comment by TheLastProject** [comment]
Sure, go for it! :)

**Comment by SamarthAsthan** [comment]
@TheLastProject was this what you were talking about? the tick that is coming?

https://user-images.githubusercontent.com/97031010/180137809-2a78e245-93dc-4050-9bd3-e14d31c8902b.mp4

**Comment by TheLastProject** [comment]
Specifically the background. The green becomes fully black. It would be good if it just became a darker green or something, so you can still easily see it was the green card you selected.

(Well, in your example it is green, ir could be any colour or even an image)

**Comment by SamarthAsthan** [comment]
@TheLastProject Select which one looks good and also now working on image

![Spring Floral Collage Wallpaper (1)](https://user-images.githubusercontent.com/97031010/180282931-d143ba4a-e04b-4ebe-b318-0a13439f68cf.png)

**Comment by TheLastProject** [comment]
I think black looks best, because it keeps the original image closest to the original but the checkmark is still readable :)

**Comment by SamarthAsthan** [comment]
> I think black (number 2) looks best, because it keeps the original image closest to the original but the checkmark is still readable :)

so should i remove this white tick mark or let it be?

**Comment by TheLastProject** [comment]
Keeping it white looks best I think

**Comment by SamarthAsthan** [comment]
@TheLastProject ok let me I finalize it and theni will put a pull request
