### ISSUE TITLE
Save expansion state

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#707]
The icon to show / hide details always starts at showing details after a clean start. It would be good to save this to the last used case.

It should also be possible to toggle this setting in group edit and selecting a card for a shortcut (by putting that in the menu), to prevent the saved default from making it hard to tell what card you want.

**Comment by roshavagarga** [comment]
Small addition, if I understand what this is (the toggle icon after the search one, second from left to right), there is a small visual bug with it - when you click on the order symbol to its right, the tap animation starts from the center of the symbol, while on the toggle icon - it shifts based on where you tapped on the symbol. If I am wrong in thinking that you're talking about a function linked to that toggle - this could be added as a separate bug report.

**Comment by TheLastProject** [comment]
That's a separate issue, yeah. Also something way too minor for me to personally care about (Android is a messy platform and those are the types of issues that will cost many many hours to solve that I'd rather spend differently), but if you want you can make an issue report for it. I just won't bother fixing it myself, so it'd only be there to be written down in case someone else wants to spend hours on fixing it.

**Comment by TheLastProject** [comment]
Got a request for this by email, so bumping it a bit more to the front of the backlog again.

**Comment by TheLastProject** [comment]
Fixed in 4680b53f86977f19594f47a1f691e9290b33e1aa.
