### ISSUE TITLE
Emoji in card name doesn't display well in card view

### ISSUE THREAD

**Issue by Altonss** [CatimaLoyalty/Android#711]
This is a minor bug, but emojis have a small 'white dots' in the background. I don't know if this is reproducable on other devices, but just wanted to document this 'little bug' here :)

![image](https://user-images.githubusercontent.com/66519591/147880733-62e46e69-a716-44e3-9303-b775e3c98d12.png)

System information:

Android 5.0.1
Device: Samsung Galaxy Core Prime

**Comment by TheLastProject** [comment]
I can't reproduce this, so I am going to chalk this up as an Android 5 specific thing again.

**Comment by Kethen** [comment]
looks like a samsung issue
<img src="https://user-images.githubusercontent.com/22017945/154817312-a89b25d7-c444-4708-9347-3e693fa6d1d6.png" width=50% height=50%>
