### ISSUE TITLE
Xiaomi 11 5G lite (Android 11): Can't select image from gallery as photo

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#729]
Reported to me by e-mail, apparently the gallery opens and you can select a picture, but when you come back to Catima the picture isn't there.

I can't reproduce this on my Android 11 device, so seems to be Xiaomi-specific. Need someone with a Xiaomi device to debug and fix this.

**Comment by TravonteD** [comment]
Hi, Im ona Xiaomi Poco X3 Pro (android 11), and selecting an image from the gallery works flawlessly for me. (Tested using the stock app). So, I dont think this is a xiaomi problem per se. Also thamks for your work, this app is awesome!

**Comment by TheLastProject** [comment]
Thanks for the update! Whatever is happening is most likely specific to a certain file manager or something on their device or just misunderstanding the UI. I've emailed them back to ask them to screen record the issue, I'll mark this issue as "needs info" so it will automatically close after a while if I don't hear anything back.

**Comment by baudav** [comment]
screencast uploaded: https://youtu.be/__saFdbZ8gA

**Comment by TheLastProject** [comment]
Okay, yeah, that is... really weird and I can't reproduce it myself.

So we can confirm that Catima does manage to start the gallery, but someone doesn't respond correctly to the data it gets back (if any).

I've created a debug version that will show more info to help understand better what's going wrong. Could you please record the screen again with this version? Then I can hopefully figure out why this is going wrong: [app-debug.zip](https://github.com/CatimaLoyalty/Android/files/7875475/app-debug.zip).

Could you also please attach one of the images that this is going wrong with (inside a .zip file so nothing will mess with the image file) so we can be certain that the image file itself isn't somehow causing this?

**Comment by baudav** [comment]
The message displayed after select photo or file 
![debug](https://user-images.githubusercontent.com/10183995/149632845-712afc83-9587-4d46-b1b2-f1c957808ae6.jpg)

It's same for all images or photos. Image work fine on my device (I share it from my device). And add image from galerie or File Manager work fine with Hangouts, Gmail... example image below
[example.zip](https://github.com/CatimaLoyalty/Android/files/7875549/example.zip)

**Comment by TheLastProject** [comment]
...Are you kidding me, Xiaomi returns CANCELLED after success? What the hell... Well that's the problem...

**Comment by baudav** [comment]
?? bad understanding of my bad english??

**Comment by TheLastProject** [comment]
Well, according to your screenshot, you didn't select a photo but pressed "cancel" instead. If you didn't, then Xiaomi is doing something very very wrong and I don't know if there is anything I can do at all (it's clearly an Xiaomi bug, but maybe there is a way to trick Xiaomi into behaving correctly).

**Comment by baudav** [comment]
No, I select picture (same as screencast)
I make the same operation when choice photo/picture to sent with Gmail or Hangouts and work fine.
I tested with GooglePhoto before, but it's same, return to app without error and no crop selection.. (I can retest with Google Photo and your debug version to check message)

**Comment by baudav** [comment]
With the video. https://youtu.be/83dyN2fIKLI . no joke.. I would never have dared to do that.

**Comment by TheLastProject** [comment]
So it really is as insane as I thought: Xiaomi literally tells Catima you cancelled image selection even though you clearly didn't.

There must be some way to make Xiaomi devices behave, but this is... definitely a Xiaomi bug and not a Catima bug. Do you have any way to get a logcat? Maybe the OS does write something to logcat to explain why it did this?

Hopefully I will figure out a fix after hours of searching the web... :(

**Comment by baudav** [comment]
I've found; as you said, problem with the device. I ended up seeing that 2 Gallery applications were present (probably a system version upgrade that went wrong). After removing this obsolete xiaomi component, set Gallery to default.. it works :D
In fact the other applications use the android file selector which then allows you to select the gallery.

**Comment by TheLastProject** [comment]
But didn't it also go wrong with Google Photos?

**Comment by baudav** [comment]
[logcat1.txt](https://github.com/CatimaLoyalty/Android/files/7877196/logcat1.txt)
[logcat2.txt](https://github.com/CatimaLoyalty/Android/files/7877198/logcat2.txt)

In fact, it wasn't even deleting the old Gallery that solved it, it was setting Gallery as the default program that solved it. By deleting Galerie from the default.. the problem returns. By setting Gallery as the default tool and exiting/relaunching Catima.. it works.

**Comment by baudav** [comment]
This is a bug with xiaomi device (no problem before android 11), in de Android developer options, you have to keep 'MIUI optimization' enabled.

**Comment by TheLastProject** [comment]
Wow, that is obscure. I am glad you found the issue and I will remember that if I ever get more such reports, thank you!
