### ISSUE TITLE
NFC support?

### ISSUE THREAD

**Issue by parabolapersuader** [CatimaLoyalty/Android#746]
NFC cards are becoming more common, and NFC phones as well. Could you add NFC card support?

**Comment by TheLastProject** [comment]
Duplicate of #166 and #668.

**Comment by parabolapersuader** [comment]
Not as in Google Pay, but as in my library card which is quite a static thing, like the barcode.

**Comment by TheLastProject** [comment]
What is written in #166 still stands.
