### ISSUE TITLE
Zoom beyond 100%

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#751]
Requested through email. Surely it is easy to change the slider to go above 100%, but then how to implement which area to zoom without breaking swiping to switch between pictures?

Not sure if worth implementing as you can crop part of an image already when you set it, but creating this issue anyway to collect ideas.

**Comment by Altonss** [comment]
Which slider/zoom is meant here? The zoom when displaying a qr-code/barcode in fullscreen?

**Comment by TheLastProject** [comment]
Yeah

**Comment by Altonss** [comment]
> It's the same slider, if you set a photo you can switch between barcode and photo by swiping left/right on the barcode.

Well, it's great I just discovered a new feature!
Personally I think it is too clumsy to add this zoom beyond 100%. There is already the crop possibility when choosing the picture, so I don't really see the point of having this additionnal feature. I understand the potential use case, but it would be to rethink all the current logic for a not so great benefit...

**Comment by TheLastProject** [comment]
Yeah, I'm having the same feeling. So I guess this is consensus too: consensus to label it wontfix :)

**Comment by Altonss** [comment]
> Yeah, I'm having the same feeling. So I guess this is consensus too: consensus to label it wontfix :)

If someone has a different opinion feel free to comment :)
I guess what you could say to the user which requested this feature, is that he can crop his image beforehand (with the ucrop dialog) :)
