### ISSUE TITLE
Make setting a custom icon more obvious

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#763]
[It's been supported for months already](https://github.com/CatimaLoyalty/Android/discussions/756#discussioncomment-1997203) but I keep getting emails about this. Like, every few days. So this is clearly not obvious to find for people and needs to somehow be made easier to find.

**Comment by ouzowtf** [comment]
Maybe a little pencil icon in the bottom right corner could help to identify as editable

**Comment by TheLastProject** [comment]
That sounds like a great idea :)

**Comment by TheLastProject** [comment]
Fixed in 34bbfffdafa5c2ff525eeffc4eef44fd05684f87.

It doesn't look great, but hey, it works. This change may bump up Catima's Google Play review by a serious amount because people KEEP asking for this feature and don't understand me when I tell them they can tap the letter.

![image](https://user-images.githubusercontent.com/1885159/181354361-05c0f260-289e-4d8e-9fd9-c1fb2f0b8663.png)
![image](https://user-images.githubusercontent.com/1885159/181354406-6fa5fce2-6a20-42ec-bd04-53d9624598c5.png)

**Comment by TheLastProject** [comment]
Reopening because I still get complaints like once a week from users that you "can't set a custom icon" and "the colour is automatically chosen and you can't change it".

I have no clue how to make this obvious to people, maybe the pencil stuff needs to just completely cover the whole thing? Who knows. This is so freakin' annoying.

**Comment by jmanan088** [comment]
Hey @TheLastProject can i work on this, i know i'm already assigned to one other just now, but as you said that is quite troublesome, and I'm not much experienced. We can make the whole thing covered with pencil icon while displaying no color while creating the card to make it more obvious.

**Comment by TheLastProject** [comment]
I think we should still display the current colour and possibly even the text but just resize the "button" in the corner to cover the whole thing so the pencil will be big and have enough contrast.

We may have to try a few versions before we find something that feels right :)

Assigned it to you :)

**Comment by ouzowtf** [comment]
Maybe using the complete lower half

**Comment by pfaffenrodt** [comment]
If it so important, why not making it larger.
![image](https://user-images.githubusercontent.com/5681688/198726974-6da8ff62-ae94-4a85-8ddc-7d05d6962819.png)

The Icon looks pretty good and actually obvious. Wouldnt change it.
Maybe they what something different. Like an additional option to choose an Icon/Symbol from an set of icons.

Or an FAQ page like so:
![image](https://user-images.githubusercontent.com/5681688/198727539-d7dbfb07-c943-421c-a3db-4c603885812a.png)

**Comment by TheLastProject** [comment]
> If it so important, why not making it larger. ![image](https://user-images.githubusercontent.com/5681688/198726974-6da8ff62-ae94-4a85-8ddc-7d05d6962819.png)

Because my Fairphone 3 doesn't have a small screen but even on that it already doesn't all fit when the barcode image is shown. So we already use too much space.

> The Icon looks pretty good and actually obvious. Wouldnt change it. Maybe they what something different. Like an additional option to choose an Icon/Symbol from an set of icons. Maybe Emojis? Emoji as first letter actually works

Yeah I think it is pretty obvious too, but given the amount of complaints I keep getting that you "can't set an image" (they say image or photo always) it clearly isn't working. If they wanted something different that an image, I'd assume the reviews would use another word like "icon" or "emoji" or so?

> Or an FAQ page like so: ![image](https://user-images.githubusercontent.com/5681688/198727539-d7dbfb07-c943-421c-a3db-4c603885812a.png)

Sadly nobody ever reads the FAQ. The world would be a better place if people did :)

**Comment by pfaffenrodt** [comment]
> So we already use too much space.

ScrollView is no option? Users with small devices are used to it? especially in froms

**Comment by TheLastProject** [comment]
There is already a ScrollView, but I don't want to make the spacing issue worse. I also quite like the existing layout with the image preview next to the name and think making it use a full line will look a lot uglier :(

**Comment by TheLastProject** [comment]
With the new redesign, we have a nice place where we can do this.

In the new loyalty card view screen, we could make it so that clicking the header image will show the same options as in the edit screen:
![image](https://github.com/CatimaLoyalty/Android/assets/1885159/9dcc7831-09db-44da-af0b-8ce9a1985651)

Then, if you click one of those options, it would start the LoyaltyCardEditActivity in the state where you just selected that option for the cleanest code (and we inherit a consistent UI and a way to confirm things for users)

**Comment by TheLastProject** [comment]
The new layout puts this new icon front and center. I just made it clickable in 419d28163ebec8c4c383d855fc4d9c485e1a6bf0.

I really hope that'll be the end of this feature request, but we'll see :sweat_smile:
