### ISSUE TITLE
Add padding to bottom of main list

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#764]
So the FAB doesn't overlay the last card if you scroll all the way down:

![image](https://user-images.githubusercontent.com/1885159/150701148-8ddb1ff4-e3db-4655-a78e-7e9be81be05d.png)

When this is fixed, the whole "Shoe Store" card would be visible when scrolled all the way down.

**Comment by apollofps** [comment]
Hi i would like to work on this issue .

**Comment by TheLastProject** [comment]
Go for it :)

**Comment by ratneshnavlakhe** [comment]
Hi @TheLastProject is this issue already fixed or in progress, would like to pick this up.

**Comment by TheLastProject** [comment]
@apollofps requested to do this just yesterday. Let's give them a few days, if I don't hear from them it's yours.

**Comment by TheLastProject** [comment]
Because I haven't heard any progress from @apollofps since they claimed this issue 1 week ago it's now yours @ratneshnavlakhe.

**Comment by ratneshnavlakhe** [comment]
Hi @TheLastProject i am new to this app can you tell me how do I populate the screen with cards, I am not sure I have barcodes with me, can you help here ?
