### ISSUE TITLE
Color issue with the new theming (crop feature)

### ISSUE THREAD

**Issue by Altonss** [CatimaLoyalty/Android#767]
Like already discussed in this discussion https://github.com/CatimaLoyalty/Android/discussions/749 , the new theme brings some issues to the color theming.
When being in dark mode the cropping bar on top is white. This has too issues:
- a white bar is odd for a dark theme (which is not a big issue because the cropping menu is rare, but still!)
- the notification bar is not visible at all! (here a sreenshot):
![image](https://user-images.githubusercontent.com/66519591/151213831-3d3dc528-4319-4f98-9e46-6ac819dd9ce7.png)

**Comment by TheLastProject** [comment]
That shouldn't be white though, sounds like I broke that by accident when implementing Material You.

**Comment by TheLastProject** [comment]
Fixed in 9887e19ec9dfbded5b730ab39654d319cc6f39a3.
