### ISSUE TITLE
Power screen cards, lock screen and unlock

### ISSUE THREAD

**Issue by djechelon** [CatimaLoyalty/Android#776]
This is probably not a problem with Catima itself.

On AOSP 12, I get a widget on the lock screen with the "home" icon that points to the power screen widgets (now called Device Controls).

**Without unlocking**, I can successfully display the list of cards that I chose to put under Device Controls. But when I touch one to open it, e.g. I am going to scan it at the supermarket to get a handheld scanner, Android prompts me for unlocking the device.

When I display a card in Catima, it will be available without unlocking the screen. E.g. I can turn on/off the screen and the card is directly displayed.

I just wanted to address this issue, I am not fully sure Catima can address it with its own code. The idea is that I could be able to display Device Controls loyalty cards without unlocking the screen.

**Comment by TheLastProject** [comment]
I don't think there is anything Catima can do, so I am closing this as invalid and blocked by upstream. If you have any reason to believe Catima can do something feel free to reopen.

**Comment by danielphan2003** [comment]
Hi! I was wonder around and found https://github.com/droserasprout/com.github.droserasprout.lockscreencamera

My anx camera can be used on lockscreen without needing to unlock the screen. Maybe Catima can do the same?

If using root is not an option, how about the references that the app uses? Currently I can access Google Home control on lockscreen without unlocking, so maybe there is an API that it is using for this?
