### ISSUE TITLE
Save password into setting to be used to encrypt backups

### ISSUE THREAD

**Issue by trymeouteh** [CatimaLoyalty/Android#781]
To do an encrypted backup, one needs to either remember the password they use or go into their password manager, copy the password they use, and paste it into the password field before creating an encrypted backup.

Please consider adding a setting in Catima to store the password that can be used when creating an encrypted ZIP backup, this will make the encrypted backup process easier.

**Comment by TheLastProject** [comment]
I understand why you're asking for this, but I am not really convinced this is an improvement. It complicates the codebase at a pretty critical path (exporting your data) and primarily increases the risk of users creating backups with a password they forgot. Using a password from your password manager should only be like one or two taps anyway, so the additional benefit is very small while it complicates the export code (and thus the risk of an export not going well).
