### ISSUE TITLE
Color bug with photo

### ISSUE THREAD

**Issue by Altonss** [CatimaLoyalty/Android#803]
When having a barcode card with one photo stored and the background set to green for exemple the following bugs happend on 2.15 with dark theme:
- enter card view
- switch to the photo by swiping (instead of the barcode)
- open the photo in fullscreen
- go back, and now the green color background has disappeard and is black!

**Comment by Kethen** [comment]
Cannot reproduce on android 5 and 12 emulator

**Comment by TheLastProject** [comment]
It is not very consistent, but I can sometimes reproduce it on Android 11. You almost triggered it in the start of your video.

I wonder if it's an issue with Material You (Material3) libraries on pre-Android-12.

https://user-images.githubusercontent.com/1885159/154674579-f80de052-4afc-44d7-b111-0ba61b9c9579.mp4
