### ISSUE TITLE
Catima doesn't support new Android themed icons

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#809]
https://developer.android.com/about/versions/13/features#ux

![image](https://user-images.githubusercontent.com/1885159/153582532-ae66003e-0f8f-4ecf-8717-d00205572a28.png)

**Comment by Altonss** [comment]
Maybe this can help, I don't know... https://github.com/signalapp/Signal-Android/pull/12385/files

**Comment by TheLastProject** [comment]
@TangentFoxy looked into this and suggested something like this:

![greyscale](https://user-images.githubusercontent.com/1885159/185711869-a4cd8254-a91b-4a49-b2e7-ae934938f9b0.svg)

We both have no clue how to translate it to XML though. @Donnnno, could you help perhaps? Feel free to tweak the concept to fit better :)

**Comment by Donnnno** [comment]
Hi, I can take a look tomorrow!

**Comment by Donnnno** [comment]
Hey, I've played around with the icon and this is what I've come up with for the monochrome icon:

![image](https://user-images.githubusercontent.com/31142286/185745179-59563a96-4b15-470c-bd28-0a5b52c38cae.png)

**Comment by TheLastProject** [comment]
Hmm, I worry it may be a bit much contrast compared to the other icons. But Google doesn't really seem to have guidelines for this kind of stuff. I think it may be worth  looking into making the bright parts less bright (except the eyes, that's consistent with the messaging icon for example) but I guess that may also make everything blend together.

Bleh, art is hard, if you think this is fine I'll just trust your judgment :)

**Comment by Donnnno** [comment]
and how about this?

![image](https://user-images.githubusercontent.com/31142286/185745929-88ffeefc-c6cd-41d9-af5c-716713ebfa4d.png)


Google made the use of transparencies possible, so it wouldn't be weird if more icons end up use it eventually :)

**Comment by TheLastProject** [comment]
Yeah I think that looks much better :)

**Comment by Donnnno** [comment]
Great :)
