### ISSUE TITLE
Hide beta importers until long-press

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#815]
It seems Stocard might be broken, got several complaints over email.

Everyone refuses to share their export file for privacy reasons.

Some people are leaving negative ratings on Google Play just because of this.

I want the beta importers to be hidden on normal press of the import buttons (shown on long-press only), so that only technical users will even have access to these options.

**Comment by TheLastProject** [comment]
Actually, no, screw it. "Beta" is clear as a "may not work". End users just need to complain less and help more if they want stuff fixed, especialy stuff marked as beta.

**Comment by Altonss** [comment]
Do we know what exactly broke with stocard? Did their file structure change?

**Comment by TheLastProject** [comment]
No clue, multiple people reported it and everyone refuses to share their export file so I can't debug this.

**Comment by Altonss** [comment]
Well I don't have stocard, so I'm will not be able to help you :/

**Comment by Altonss** [comment]
A fix is probably on the way to fix the borken Stocard import. See this issue https://github.com/CatimaLoyalty/Android/issues/843 and the fix #844 :)
