### ISSUE TITLE
Android 5: Catima 2.4.0 doesn't start anymore, crash at startup

### ISSUE THREAD

**Issue by Altonss** [CatimaLoyalty/Android#840]
After having opened the new 2.4.0 and played with it, the app now doesn't start anymore

**Comment by TheLastProject** [comment]
Do you have any crash logs? https://github.com/TacoTheDank/Scoop is the easiest way to get them in my experience

**Comment by Altonss** [comment]
> Do you have any crash logs? https://github.com/TacoTheDank/Scoop is the easiest way to get them in my experience

I will try to install it, and get back to you when I have more info! Thanks for the tip!

**Comment by Altonss** [comment]
I installed scoop and followed the steps, but the crash hasn't been recorded by scoop :/

**Comment by TheLastProject** [comment]
That is weird. Guess the only option you have is getting a logcat the normal way. I sadly can't do anything about a crash without a crash log :(

**Comment by Altonss** [comment]
I have this:
`
D/AndroidRuntime(13720): Shutting down VM
E/AndroidRuntime(13720): FATAL EXCEPTION: main
E/AndroidRuntime(13720): Process: me.hackerchick.catima, PID: 13720
E/AndroidRuntime(13720): java.lang.RuntimeException: Unable to start activity ComponentInfo{me.hackerchick.catima/protect.card_locker.MainActivity}: android.database.sqlite.SQLiteException: Can't downgrade database from version 14 to 10
E/AndroidRuntime(13720): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2474)
E/AndroidRuntime(13720): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544)
E/AndroidRuntime(13720): 	at android.app.ActivityThread.access$900(ActivityThread.java:163)
E/AndroidRuntime(13720): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
E/AndroidRuntime(13720): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(13720): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(13720): 	at android.app.ActivityThread.main(ActivityThread.java:5608)
E/AndroidRuntime(13720): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13720): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(13720): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
E/AndroidRuntime(13720): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)
E/AndroidRuntime(13720): Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 14 to 10
E/AndroidRuntime(13720): 	at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:360)
E/AndroidRuntime(13720): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)
E/AndroidRuntime(13720): 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
E/AndroidRuntime(13720): 	at protect.card_locker.DBHelper.getLoyaltyCardCursor(DBHelper.java:485)
E/AndroidRuntime(13720): 	at protect.card_locker.MainActivity.updateLoyaltyCardList(MainActivity.java:397)
E/AndroidRuntime(13720): 	at protect.card_locker.MainActivity.onCreate(MainActivity.java:237)
E/AndroidRuntime(13720): 	at android.app.Activity.performCreate(Activity.java:5993)
E/AndroidRuntime(13720): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
E/AndroidRuntime(13720): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2427)
E/AndroidRuntime(13720): 	... 10 more
`

Logcat gives a lot of lines, so I just selected these. If you need more I can look further :)

**Comment by TheLastProject** [comment]
It is trying to downgrade the database. That makes no sense to me. Are you sure this is from upgrading Catima? It sounds more like you are building Catima from source, then tried to switch to an older version or manually edited DBHelper.java.

Given DATABASE_VERSION has been 14 since October last year (https://github.com/CatimaLoyalty/Android/commit/127d53e85ac5e468d7e9a5e225f799439f617c93) I really don't see how this can happen during a normal Catima update.

**Comment by Altonss** [comment]
I really don't understand too :( I once installed other builds, but these were always separate to my "stable" build from fdroid

**Comment by Altonss** [comment]
> It is trying to downgrade the database. That makes no sense to me. Are you sure this is from upgrading Catima? It sounds more like you are building Catima from source, then tried to switch to an older version or manually edited DBHelper.java.

After the update it worked once. And then I wanted to start the app again and then nothing...
Should I try to downgrade and then upgrade again through fdroid?

**Comment by TheLastProject** [comment]
Wait, I just noticed you wrote 2.4.0. But the latest version is 2.16.0? 2.4.0 is quite old.

2.4.0 was database version 10: https://github.com/CatimaLoyalty/Android/blob/78481516b0a06dab18ad442b92a2f2226e2f0600/app/src/main/java/protect/card_locker/DBHelper.java#L25

So if you were trying to downgrade a recent version to 2.4.0 that would make sense. However, Android shouldn't allow you to downgrade apps at all without deleting all data exactly to prevent issues like this.

> Should I try to downgrade and then upgrade again through fdroid?

I am so confused. Do you run some kind of custom ROM or root tool that allows you to downgrade apps even though that normally shouldn't be possible or something?

**Comment by Altonss** [comment]
No I am running a stock rom, I am really confused because only update the app with fdroid...

**Comment by TheLastProject** [comment]
Sorry, I really don't understand. This goes against everything I know about Android :(

**Comment by Altonss** [comment]
I am sorry to bother you with this. I will try to downgrade and update.

**Comment by Altonss** [comment]
it works again now...well this was really strange :rofl:
