### ISSUE TITLE
Can't import from Stocard

### ISSUE THREAD

**Issue by sergius02** [CatimaLoyalty/Android#843]
Hi! I have a *-sync.zip with all my data from Stocard. But when i try to import in Catima, the import dialog never ends.

<details>
<summary>Screenshot</summary>

![catima](https://user-images.githubusercontent.com/10380412/159459346-68fb25f7-ada0-4fed-9df9-31a1ae67c84e.jpg)

</details>

**Comment by sergius02** [comment]
> I've had multiple people report issues like this to me (mostly by email). Given the unit tests and my own export file work fine, I will need the export file of an affected user to be able to reproduce this.
> 
> Could you please email your export file to [catima.g9ex3@hackerchick.me](mailto:catima.g9ex3@hackerchick.me) so I can take a closer look?

Done!

**Comment by TheLastProject** [comment]
I got your export, thanks a lot! I found a few bugs I am going to fix in #844. I'll give you a heads up and a custom build when it seems to work for me so we can confirm it works as intended :)

**Comment by sergius02** [comment]
All my cards are imported with the debug app from https://github.com/CatimaLoyalty/Android/pull/844#issuecomment-1075638893 😀

**Comment by TheLastProject** [comment]
Thanks for your report, export file and help testing! The improved Stocard import will be part of the next release. I will probably release it to F-Droid and Google Play Open Testing over the weekend to give the translators a day or two to translate the changelogs
