### ISSUE TITLE
Stocard import fails (NullPointerException) 

### ISSUE THREAD

**Issue by PhoenixWyllow** [CatimaLoyalty/Android#863]
Using Catima 2.16.2 (google play) - also happens on 2.16.1 (fdroid) 
Android 12 (OnePlus 9 Pro) 

![Screenshot_2022-04-14-11-24-06-52_0e0fb5e4c7b0c70cd406dc034ad65059.jpg](https://user-images.githubusercontent.com/54237626/163355931-edea2652-8447-492b-b74c-8182610131be.jpg)

Repro steps:
Import Stocard zip from filesystem
Add password in email

Additional issue: 
Catima seems to become unresponsive and needs to be removed from recent apps. Reopening the app is as normal.

Notes:
I'm not sure if it's a quirk, but ZArchiver and TotalCommander (android app) open the zip without needing a password.

**Comment by TheLastProject** [comment]
I fixed some Stocard import issues in #843 which was enough to make the import succeed for some people, but I guess there are still some issues left for some Stocard files. The exact error you get confuses me a bit, but luckily there aren't many places in StocardImporter.java this could go wrong so hopefully it's a quick fix.

Could you please email your export file and password to [catima.g9ex3@hackerchick.me](mailto:catima.g9ex3@hackerchick.me) so I can take a closer look?

> I'm not sure if it's a quirk, but ZArchiver and TotalCommander (android app) open the zip without needing a password.

Most likely Stocard password-protects the actual files and not the file index, I assume ZArchiver and TotalCommander will probably need a password when you try to extract any of the files in the zip.

**Comment by PhoenixWyllow** [comment]
Sent! Many thanks for taking time to look into this.

**Comment by TheLastProject** [comment]
Thanks for the export file! Your export had 2 cards that had only images and no actual card data. My expectation is that those are deleted cards that Stocard deletion script didn't correctly delete the coupled images from.

I've implemented a workaround to ignore those cards in 1872bea0c305b189ed5aacc4dd60b1fbdd36d6a3, which will be part of the next release.

I've attached a debug build you can sideload if you want to test yourself without compiling: [app-debug.zip](https://github.com/CatimaLoyalty/Android/files/8492053/app-debug.zip)

The import result looks fine to me, so I'm going to close this under the assumption I fixed your import issue. If you notice anything wrong with your import, please tell me (feel free to email again if you consider it private) and I'll look into whatever you noticed :)

**Comment by PhoenixWyllow** [comment]
Flawless! This fixes the issue. Thank you so much :)

**Comment by wazyk** [comment]
Hello @TheLastProject 
I just encountered the same NullPointerException on a Stocard zip import (on latest Goggle Play Catima version).
I confirm that your debug apk fixes the issue for me too, thx !

**Comment by TheLastProject** [comment]
@wazyk Glad it works for you too, good to know :)

Btw, there's not necessarily a "latest Google Play Catima version" as I always do staged rollouts so that if I make a mistake causing breakage it won't break for all of the almost 9000 users at the same time. Currently, 100% of Google Play Open Testing is on 2.16.3 and 30% of production is. If you want the fixed version early, I suggest joining the Open Testing program. Otherwise I expect 100% availability in a week (I generally increase the availability with 10% a day unless something happens or I have a reason to be extra careful).
