### ISSUE TITLE
Calibre action not running

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#915]
It should've ran on this commit: https://github.com/CatimaLoyalty/Android/commit/aa069e93b1c843ce22e5558980ca225430f4e9ae

Pretty sure paths in GitHub Actions is wrong and that's it.

**Comment by TheLastProject** [comment]
![image](https://user-images.githubusercontent.com/1885159/175697078-2cc7998b-feba-4cac-90f8-675dadb3dcf3.png)

Oh, I've never seen these warnings :sweat_smile:

**Comment by TheLastProject** [comment]
Hmm, actually, that can't be it, I'm referencing 1.1.0...

**Comment by pfaffenrodt** [comment]
@TheLastProject did it run in the past ? https://github.com/CatimaLoyalty/Android/actions/runs/2558094264/jobs/3937452632

**Comment by TheLastProject** [comment]
It did run long long long ago. And yes, it was skipped, but it shouldn't have been, it should have checked the images. That's the bug.

**Comment by pfaffenrodt** [comment]
Could you try to create a Branch with the name main?

with the workflow adjustment
```
name: Compress Images on Push to Master
on:
  push:
    branches:
      - main
```

**Comment by TheLastProject** [comment]
I don't think that's the issue, given the branch name currently is master (I should probably change that at some point, just always worried about possible random breakage).

My best guess is that the paths stuff possibly doesn't work as expected (we can perhaps even remove the branch limit so it runs on PRs too because overly large images get merged)

**Comment by TheLastProject** [comment]
I ended up just deleting the action, I'll use optipng locally.
