### ISSUE TITLE
navigation bar color

### ISSUE THREAD

**Issue by andsofine** [CatimaLoyalty/Android#917]
change nav bar color (black) to light/dark theme background color
![AFFIX_20220627_210557.png](https://user-images.githubusercontent.com/99369164/176007156-41315754-ab22-43d7-af1f-ac1525618007.png)

**Comment by TheLastProject** [comment]
I need a bit more info here, as far as I know that is already what is happening. But I can't do much testing because Material Colours are only becoming available to all devices on Android 13.

Can you please use screenshots and point out what you mean exactly?

**Comment by TheLastProject** [comment]
> and material colors became available with android 12l didn't it?

Only for some devices, Google has an allowlist. Fairphone is not on that allowlist so I can't test on my device.

https://www.androidpolice.com/material-you-android-13-allowlist/

Not sure if this is even a Catima bug though, it may just be a bug/weird behavior in Google's Material library.

**Comment by TheLastProject** [comment]
If I look at the screenshots in Google's Design Guidelines (https://m3.material.io/components/top-app-bar/overview) the top bar is a different colour than the background so... it seems to me this is probably how it's supposed to be?

**Comment by Altonss** [comment]
I don't see the issue neither, since the UI refresh Catima has always looked like this for me too :)

**Comment by Jean-BaptisteC** [comment]
Check this -> [Support for lollipop devices while using windowLightStatusBar](https://medium.com/@SindkarP/support-for-lollipop-devices-while-using-windowlightstatusbar-362777886393)
Maybe add this item on theme ?

- [windowLightNavigationBar](https://developer.android.com/reference/android/R.attr#windowLightNavigationBar) 
- [windowLightStatusBar](https://developer.android.com/reference/android/R.attr#windowLightStatusBar)

**Comment by Altonss** [comment]
> Can i fix problem ?
> 
> I have just need to add new res themes day/night v23 and v27 with this items:
> 
>     * v23 light
>       `<item name="android:windowLightStatusBar">true</item>`
> 
>     * v23 dark
>       `<item name="android:windowLightStatusBar">false</item>`
> 
>     * v27 light
> 
> 
> ```
> <item name="android:windowLightStatusBar">true</item>
> <item name="android:windowLightNavigationBar">true</item>
> ```
> 
>     * v27 dark
> 
> 
> ```
> <item name="android:windowLightStatusBar">false</item>
> <item name="android:windowLightNavigationBar">false</item>
> ```

If you have an idea/fix you, feel free to open a Pull Request :) I think @TheLastProject is probably busy that's why your suggestion hasn't been tested yet, but I (and the small Catima team in general) would be very happy to review your PR!

**Comment by TheLastProject** [comment]
What Altonss said, go for it. I can review as soon as I have time :)

**Comment by TheLastProject** [comment]
Sorry, merging the fix introduced new bugs. So I had to revert it in https://github.com/CatimaLoyalty/Android/pull/1015.

**Comment by tripathisharad** [comment]
Hi there can you assign this project to me so that I can try to solve the problem.

**Comment by TheLastProject** [comment]
Sure, go ahead :)

**Comment by TheLastProject** [comment]
I'm not putting the original fix back in because it had really bad bugs (see #1015) but would love to merge a proper fix to this. I just don't have enough time to fix all the issues myself quickly so contributions will speed this up severely.

**Comment by TheLastProject** [comment]
As far as I noticed in testing that seemed to be the only issue.

Thanks for those links. Sadly that's not a complete solution because that StackOverflow post states "Starting from API 27" and Catima supports API 21 and up. However, if no solution going all the way back to API 21 can be found it may be worth seeing if it is possible to properly style the bar on API 27 and up and stick to the old behavior for 21 - 26 so people on newer Android versions have a nicer style without breaking anything for those on older Android version.

**Comment by TheLastProject** [comment]
This issue has been duplicated downstream on https://github.com/ziadOUA/zCard/issues/16 (so I'll have to watch that too to see if anything happens there we can merge back into Catima)

**Comment by candroid-man** [comment]
Any update on this? Still occuring in Android 13 as well as GrapheneOS (tried both)

**Comment by TheLastProject** [comment]
It looks like zCard may have fixed this in https://github.com/ziadOUA/zCard/commit/b867b33f537c325b3ec9f3714bc28e5034efefd7

We should investigate this commit, confirm if it works well and if it does include it into Catima.

**Comment by obfusk** [comment]
Was it correct to close this? #1547 implements Android 8.1+. What about older versions?

**Comment by TheLastProject** [comment]
Looking at apilevels.com, Android 8.1+ support means 90.49% of all active devices. And the change doesn't break on any older devices. To me, that is good enough, especially for a feature as unimportant and minor as this one. Android constantly changes a lot, supporting every feature on every version ever is an unreasonably big amount of work with extremely messy code.

**Comment by obfusk** [comment]
Ack. I figured. Just wanted to make sure :)
