### ISSUE TITLE
Groups overview should show archived card count

### ISSUE THREAD

**Issue by Altonss** [CatimaLoyalty/Android#924]
I had a group with cards and I archived all the cards contained in that group. When I go to the tab of that group is says it's empty which makes sense. But when clicking on groups to manage them, I still see that the group contains a lot of cards (the archived once, but this is not displayed to the user that these are archived).

Catima version 2.17.0

**Comment by Altonss** [comment]
Yes exactly, it should say like 0 cards (2 archived cards) or something like that, because currently it is a bit confusing for a user to see 2 cards, but when going to that tab see no tab.

**Comment by Altonss** [comment]
Also when editting a group, you see non-archived cards and archived cards at the same time. This may be too much for the user, who maybe expect the archived cards to be hidden behind the "Archived" button and not visible elsewhere.
But that is just a UX issue, and it's a matter of taste. What do you think about it?

**Comment by TheLastProject** [comment]
> Also when editting a group, you see non-archived cards and archived cards at the same time. This may be too much for the user, who maybe expect the archived cards to be hidden behind the "Archived" button and not visible elsewhere. But that is just a UX issue, and it's a matter of taste. What do you think about it?

I kinda did that on purpose, so you can still use the group screen to move multiple archived cards into or out of a group instead of having to manually do that per archived card.
