### ISSUE TITLE
Default to collapsed/compact view in archived view

### ISSUE THREAD

**Issue by Altonss** [CatimaLoyalty/Android#927]
For me the default to collapsed/compact view in the archived view would make more sense in 2 ways:
- take up less space, especially because over time you might accumulate a lot of archived cards
- hide not so important infos in the context of archived cards, to make the UX clearer (infos such as the balance of the coupon, the expiry date or notes might be secondary, moreover in the context of archived cards)

This is a design idea, so I would be happy to hear some feedback ;)

**Comment by TheLastProject** [comment]
I'm not a fan of this idea. Most people either prefer full or collapsed view, so right now Catima just remembers whatever you set it to and uses that everywhere. Changing the default only on some screens would mean the collapsed view would suddenly pop up for people who prefer the full view. It will also complicate the code. So to me this would make the behaviour less intuitive and take control away from the user so I won't be implementing this or take pull requests for it.
