### ISSUE TITLE
Enhancement: add view option with names not visible

### ISSUE THREAD

**Issue by proteus077** [CatimaLoyalty/Android#964]
Love the app, just had a simple feature request for an option to be available that would show the card image at full "card" size, but not have the name visible. I have added images for all of my cards so this would allow for a cleaner look with the cards remaining easily identifiable. As this may not be a common use-case, a toggle setting for "hide card names" could live within the settings menu instead of being on the main screen.

**Comment by TheLastProject** [comment]
Given the low amount of people who will probably use this feature, I'm not sure if it is really worth implementing. However, when done, I guess it may be most sensible to just change the current "Show details"/"Hide details" toggle in the main screen into a "Display settings" button (or to just move it all to settings).

I kinda want to prevent adding more and more settings, as it just makes the app more confusing (I already get a lot of support requests which are solely about features that already exist).

**Comment by proteus077** [comment]
Totally understandable, thanks for taking the time to consider it :)

**Comment by ccrowles** [comment]
Seconding this feature, it would also look nicer (in my opinion). Personally, I use the companies' logo as card image, so the name under it is a bit redundant in this case.
