### ISSUE TITLE
Export null file

### ISSUE THREAD

**Issue by LuNiKoFf** [CatimaLoyalty/Android#967]
When exporting to backup my cards it create an empty, corrupted zip file.

I use the last Fdroid version on android 11 (lineageOs 18.1 / bacon with a One Plus One)

**Comment by TheLastProject** [comment]
Last F-Droid version... that's 2.18.1 right now, right?

I just tried an export on 2.18.2 (which has no changes in export code compared to 2.18.1) and that works fine, and I'm running LineageOS for microG 18.1 myself, so I'm not sure what's going on.

First of all, are you giving Catima time to complete the export? It can take a few seconds and moving Catima to the background while it is exporting will make the export fail (see #513).

If that's not it, do you have any special extra security/privacy things that may make Catima unable to write? Anything Xposed? What filemanager are you using to select the export location?

You say "empty, corrupted". Does that mean it's 0 bytes? If not, could you maybe send the export to me privately (an email is on my GitHub profile)?

I'm kinda grasping at straws here. Is there any crash that happens ([Scoop](https://f-droid.org/en/packages/taco.scoop/) is great for catching those)? Could you maybe record what's happening and show the permissions Catima has?

**Comment by LuNiKoFf** [comment]
2.18.1 yes.

Yes, I gave time to complete but still 0 ko file.

I don't have special extra security. I don't have xposed. I have just LineageOS. I don't even have any google apps, nor microg.
I use default filemanager from lineageOS.

Yes this is a 0 byte file.

There is no crash. When I click on save, it comes back to catima default page.

I love your application, but I am afraid to lost all my cards ^^ since I can't backup correctly.

**Comment by TheLastProject** [comment]
> There is no crash. When I click on save, it comes back to catima default page.

That sounds like a crash. That is not where export should bring you, but it is where Android restarting the app if it crashes will bring you. Please set up Scoop or something else that'll get you crash logs.

If Scoop doesn't find anything Android is probably OOM-killing Catima in which case I really have no clue what to suggest except close as many other apps as possible.

For context (and why I asked for a recording to better understand), an export is supposed to look like this:

https://user-images.githubusercontent.com/1885159/182409424-7ca8d429-cebc-4b2a-a314-0e3aa0027eae.mp4

**Comment by LuNiKoFf** [comment]
I have uninstalled app, and delete all storage files from app to have a clean install.

I exported and imported using links such as  https://catima.app/share/........

I installed Scoop, but it seems, there is no crash as you will see...
I don't have « Exporting .... » window.

Here is screen record : 
https://user-images.githubusercontent.com/6583018/183240233-4c6f4553-aecf-4edb-bd2e-2afcbff9a2ef.mp4

Thank you.

**Comment by TheLastProject** [comment]
Ouch, that's nasty, It really looks like Android kills Catima when the file manager app is open and thus the state is lost and the backup never starts.

My absolute last guess here is to check if you didn't mess around in Android's Developer options. Enabling the "Don't keep activities" developer option can cause this issue. Maybe messing with "Background process limit" could hurt it too, I don't know.

If that setting isn't enabled, I don't think there's anything I can do about this situation :(

The only thing I can say is that LineageOS should come with Seedvault for backups, so as long as you've got that enabled there should still be OS-level backups of your Catima data that can be restored with Seedvault.

I'm going to leave this open in the hope someone comes along who knows about some ways to prevent this (OOM?)-kill situation, but I personally don't think this is fixable :(

**Comment by LuNiKoFf** [comment]
Exactly ! I had "Don't keep activites" checked in developer option !
I unchecked and now it works well !

Thank you very much for your very good work !
I can close the issue.
