### ISSUE TITLE
Avast Antivirus false positive for 2.18.1

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#972]
![IMG_20220803_171932_179](https://user-images.githubusercontent.com/1885159/182645629-b692d197-48c8-470e-bbf7-8e4e0017120e.jpg)

Yeah, uhm, I have no words for this nonsense. Thanks for wasting my time, Avast.

**Comment by TheLastProject** [comment]
Reported on Avast's false positive report form.

**Comment by TheLastProject** [comment]
What an unprofessional company, still haven't gotten a response from them, what the hell.

**Comment by Altonss** [comment]
> What an unprofessional company, still haven't gotten a response from them, what the hell.

Looks like a trustworthy antivirus :))

**Comment by TheLastProject** [comment]
Avast ended up responding on Twitter: https://twitter.com/Avast/status/1556666849810649089

![image](https://user-images.githubusercontent.com/1885159/183494237-a45cf6fe-8858-418f-8b4e-758ce5dc6a6b.png)
> Hi Again - it was clean voted on July 26, so it should already be fixed. If it's not, can you DM us? Thanks!

That's weird as hell though, because the first report I got was August 3rd. Which means the reporter was more than a week behind on virus definitions? Trying to reach the user to get more info...

**Comment by TheLastProject** [comment]
Seems to really be solved now
