### ISSUE TITLE
Enhancement: Replace Additional Photos with Generic Documents 

### ISSUE THREAD

**Issue by atharen** [CatimaLoyalty/Android#977]
The [rightmost _Photos_ tab seen from here](https://github.com/CatimaLoyalty/Android/blob/75b1225b386064b84296e62ff11e7e2a5098bbf4/fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot-07.png) allows attachment of additional photos.

**This issue suggests adding functionality by allowing to add any sort of possible document/link.**

- [ ] In particular being able to add PDFs, and Web URLs - really just anything that can be linked, either locally from the device, or remotely as web link could be listed here. 

- [ ] Then the respective intended app on the device should open the link (browser for web links, image viewer for images, etc..)

- [ ] Finally, replace the tab name, with something like `Docs`, to denote the generic nature - _Tab name up for discussion_.

---

**As a use case**, this came about, since a QR code came in a PDF, but at a certain instance, I required the whole PDF, not just the QR code. 

Having the PDF linked from this tab, would be convenient.

The current approach to make this work would be to convert the PDF to an image, then add it - which is not intuitive on Android (_unless you use some 3rd party/proprietary service_)

**Comment by TheLastProject** [comment]
For Web URLs, you can just put those in Notes. Anything linkable in notes (URL, phone number, etc.) becomes clickable. So I don't think any new support for something like that is needed.

For adding non-photos, how is that supposed to work in the view screen? When you add a photo, it can get displayed in the place a barcode. Adding non-photos there doesn't fit the current flow at all:
![image](https://user-images.githubusercontent.com/1885159/183849030-74f3d93c-f93f-48a5-bc5a-7b47ad265b44.png)

Being able to crop PDF files with the current image cropper would add some basic PDF support and fit the current workflow, what specific use case do you have where that isn't sufficient?

**Comment by atharen** [comment]
Hmm, for me this all came about, because I will be using a flight boarding pass through the app, which consists of the barcode, and a PDF sort-of receipt that the airline intends for you to print - basically I would have liked that PDF to be on hand should I need it.

I mention this, as **the following should only be applicable if this is in scope of what the app wants to be** 
(_I see the app as being a barcode app, rather than a loyalty card app, which fair enough, is my fault_).

---

With this in mind, thinking a bit more about it, the best approach I would see is to expand the notes functionality, which I would go about it in the following manner:

**First of all**, I would either (1) make the Notes as a text area rather than a field, so it would be easier to add multiple lines, **OR** (2) make it as dynamic list of text fields, where one could add as many fields as desired.

---

**Secondly**, The notes column seems a bit unresponsive UI-wise, so I guess it can be made to look like an input used through chat client: like being able to attach a file from the system.

For example Telegram, to add an attachment, Github to add a link, to add an image, and Signal to search contacts by phone
![Telegram Attach Button](https://user-images.githubusercontent.com/23165475/183882797-b2e06a97-0c30-4b07-8034-7a8ad5764bf3.png) ![github_addlink](https://user-images.githubusercontent.com/23165475/183884534-aa48d949-5e95-4289-b811-623f469d5021.png) ![github_addimage](https://user-images.githubusercontent.com/23165475/183884653-5f23472a-d6ac-4610-bbd7-fa35ccb88761.png) ![signal_number](https://user-images.githubusercontent.com/23165475/183886145-4e6f649e-66c2-42f1-9034-8c4355a7ca35.png) 

1. The add attachment would be an additional feature, but it should just link to the underlying file system, either as a symbolic link, or store a copy for the app's use.
2. The add link, would just make the adding of a link, so not much to add, maybe at most provide a preview of the link, (like of that would be displayed by a shared link](https://github.com/rafaelmardojai/share-preview).
3. The add image is effectively already built-in but only for front and back, but with this button, it would filter the filesystem for pictures, and make viewing a preview even easier - would even allow the editing/resizing menu to run as a post-hook.
4. The search contacts, maybe a bit too much, and sort of don't need it now that I know about it, but I'll only mention it, because I did not know you could add phone numbers (thanks for that) - you'll probably end up requiring Contacts permission, so I would say out of scope for the moment...

---

**Finally**, as for how it could be shown within the Carousel:
1. For an attachment, (1) minimum file path/file name, (2) preferably show an icon of the file type as what would be seen in a File Explorer/Desktop (imagine Acrobat logo for PDF), (3) ideally render it (_too much effort imho..._)
2. For the link, either leave it as text, or show the preview - if showing the preview is an option, it would be ideal (some websites are not optimised for previews, so a user can omit them)
3. For an image, I would say it's already well defined so keep the current functionality - i.e. just show the image
4. For a phone number, maybe list the contact name if available, but raw number is enough.

---

One last thing to add, is to make each attachment/image open-able in the native app - even right now, I have some pictures which cannot be fully shown at 100%, but require more zoom. I would say if I were to hold the image, it should give me the option to open it in the native app.

To justify this, I would say the app is a convenience tool/app - if I need more functionality, get a proper tool/app, which would be a proper document/image/web viewer. These edge cases are out of scope to be handled within the app, but just enabling these cases to be handled easily though system integration, would be a reasonable feature add.

**Comment by TheLastProject** [comment]
Oh, that is a nice write-up, it's nice to see someone put in the effort to really describe their use case.

> Hmm, for me this all came about, because I will be using a flight boarding pass through the app, which consists of the barcode, and a PDF sort-of receipt that the airline intends for you to print - basically I would have liked that PDF to be on hand should I need it.

Hmm, does your airline not supply a .pkpass file? Because if so, your use case seems better solved by #48. Last I used it quite some years ago, https://f-droid.org/en/packages/org.ligi.passandroid/ was a pretty good app for .pkpass files (given it's not supported in Catima yet).

> I mention this, as the following should only be applicable if this is in scope of what the app wants to be
> (I see the app as being a barcode app, rather than a loyalty card app, which fair enough, is my fault).

While primarily for loyalty cards and the likes, I would consider tickets to still be reasonably within scope as they're also "things with barcodes" at the core.

> First of all, I would either (1) make the Notes as a text area rather than a field, so it would be easier to add multiple lines

It already is a text area, you can add as many lines as you want.

> Secondly, The notes field seems a bit unresponsive UI-wise [...]

I guess a nicer editing UI may be helpful in aiding discovery of the features the notes field supports. However, I'm not planning to add some of the features you are suggesting such as link previews (because that would require internet permission, Catima is proudly a fully offline app) or adding images (we already have a dedicated UI location for showing images, putting images in 2 different places harms discoverability and accessibility). I hope this is the type of situation where we can just throw is an existing well-maintained library.

> Finally, as for how it could be shown within the Carousel: [...] 

Most examples you name here are already visible in notes (just not as flashy, but see response to second point as to why). Given the only example left is a PDF, and a PDF could possibly be interpreted as an image, it seems to make sense to me to just treat a PDF as an image and make it crop-able.

I also want to avoid linking to any file outside of the app, as Google is constantly limiting filesystem access under Android further and further. Apps don't really know file paths anymore (see https://github.com/brarcher/loyalty-card-locker/issues/367) and apps outside of the app may be moved or removed at any time. I'll just import the PDF instead.

> One last thing to add, is to make each attachment/image open-able in the native app - even right now, I have some pictures which cannot be fully shown at 100%, but require more zoom. I would say if I were to hold the image, it should give me the option to open it in the native app.

100% agreed.

---

Summarizing, unless I misunderstand, I think your use case could be covered simply by:
1. Treating PDF files as images and letting them go through the cropper, making sure that multi-page PDF files will stay multi-page (probably by just putting all pages below or next to each other). (Side note: Supporting PDFs as image input also has the benefit of being able to support them in "Scan Barcode -> Select image from gallery" for new barcodes to be added, such as for #907)
2. Opening an user-installed image viewing app when long-pressing an image (or PDF-turned-image) so extended zooming, dragging, etc. become possible.

If there is demand the notes field could be made prettier, but it technically already supports all that seems needed.

**Comment by atharen** [comment]
Summary response:
1. Agreed, and more intuitive and well-thought out than my initial suggestion, so happy with that - do have some thoughts about the implementation detail of how the PDF will be imported behaviour-wise and implementation-wise further below.
2. Also agreed.

If the functionality above is met, I don't see a reason to expand on the notes field as of yet - so agreed with that as well.

With all of this in mind would you like me to open 2 appropriate tasks and define them properly from this discussion?

After that, I believe this task can be closed.

---

> Hmm, does your airline not supply a .pkpass file? [...]

I've planes, trains, and buses, and I've never seen them supply a .pkpass file - either they show the barcode, or to add to Google Pay/Wallet or Apple equivalent.
I always ended up scanning by camera, which PassAndroid could not do (I remember I had tried, and I couldn't scan by camera - though tbh, I think Catima's UX is better and seems more polished imho)

> It already is a text area, you can add as many lines as you want.

Actually used it, and it seems to work good enough - maybe overly pedantic on my part. Agreed, doesn't warrant change.

> I guess a nicer editing UI may be helpful in aiding discovery of the features the notes field supports. However, I'm not planning to add some of the features you are suggesting such as link previews (because that would require internet permission, Catima is proudly a fully offline app) or adding images (we already have a dedicated UI location for showing images, putting images in 2 different places harms discoverability and accessibility). I hope this is the type of situation where we can just throw is an existing well-maintained library.

Yeah, seemed natural to me to have access to the internet, but forgot you actually need permission for the web - agreed with the reasoning.

As for inputting images, I would have gone with one or the other - as an example using my case, I ended up converting the pdf into an image, and putting it as an image from the photos tab.

Now the existing Photos tab is intended for 2 images, front and back of card - maybe the limit on pictures could be removed? 

I'm a bit conflicted on this, in your summary you implied 1 picture per PDF (collate all pages into 1 image), I was thinking an image for each page - your suggestion works best if you have multiple PDFs, but my thinking works best when you only have 1 PDF, so you can swipe over each individual image/page. It's an implementation detail so I'll leave it to be discussed in the appropriate task.

> [...] I'll just import the PDF instead.

Huh, it's peculiar that just linking a file is getting locked down, but I can see where there are coming from - I would have assumed converting a PDF to an image would be more complex, so I did not even suggest it.

If you do opt for this, I was trying to convert my PDF on device (though ended up using my PC, as it was easier), and found 2 open-source apps which advertise this functionality:
1. https://github.com/Swati4star/Images-to-PDF which is on-going, but for me it bugs out, and someone reported there are vulnerable libraries.
2. https://github.com/scoute-dich/PDFCreator which archived for like 5 years, but worked quite well, but the UI, is poor tbh (_doesn't matter, the library is what counts_) - _if 1, had vulnerabilities, I presume this would too..._

**Comment by TheLastProject** [comment]
> With all of this in mind would you like me to open 2 appropriate tasks and define them properly from this discussion?

That sounds great.

> Now the existing Photos tab is intended for 2 images, front and back of card - maybe the limit on pictures could be removed?

Sounds like a good third issue, although I do wonder if you ever needed more than 2 images so far? We do need to at least have some limit to prevent people from throwing 100 images in there and then complaining the app "uses too much storage". Maybe 5 makes more sense (the UI could use some improving for that too, right now it's based on the idea of front and back and you can set a back image (image 2) without setting a front image).

> I'm a bit conflicted on this, in your summary you implied 1 picture per PDF (collate all pages into 1 image), I was thinking an image for each page - your suggestion works best if you have multiple PDFs, but my thinking works best when you only have 1 PDF, so you can swipe over each individual image/page. It's an implementation detail so I'll leave it to be discussed in the appropriate task.

Yeah, that is a bit difficult. One or two pages are easy enough, but if you get 5 or more pages it'll look awful.

Let's put those libraries in the new task as links and see if they're the best of if there are other options. Archived for 5 years sounds like it's asking for trouble though.

**Comment by atharen** [comment]
_Issues #496 and #977 updated and linked accordingly_
