### ISSUE TITLE
Only ask Storage permission on Android 5 and 6

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#979]
Android 13 introduces new limitations for reading files: https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

Need to check if there's a way to opt out of this or if Google effectively killed the ability to import backups when targeting Android 13.

(This is the kind of stuff that makes me hate Android development, Google's half-baked "security improvements" (what security, apps can't access files themselves the user has to select the file) where they just ignore lots of valid use cases)

**Comment by TheLastProject** [comment]
Well, "targetSdk 13 will force-decline WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE permission without even asking the user but exporting and reading a file works fine" is not a way I had expected to be able to interpret Google's "things that changed".

So it's looking like we can literally remove WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE permissions on Android 13 and we'll be fine?

Leaving this open, need to investigate this again after Android 13 goes into final and Weblate fixes the issue that prevents gradle version upgrades.

**Comment by TheLastProject** [comment]
Tests on removing `android.permission.READ_EXTERNAL_STORAGE` and `android.permission.WRITE_EXTERNAL_STORAGE` completely (need to complete):

| Android version | Adding photos from gallery | Exporting files | Importing files |
| - | - | - | - |
| 5.0 (21) | FAILS: requires android.permission.READ_EXTERNAL_STORAGE | WORKS | WORKS |

**Comment by TheLastProject** [comment]
So we can remove the storage permissions on all Android versions except 5 and 6. And the permission request on Android 6 needs to be moved to the photo picker.

Marked as bug because this could actually crash Android 6 users (yet somehow I've never seen this happen in Google Play logs yet)

**Comment by Lukmannudin** [comment]
Hi @TheLastProject , Is your mean is like this #1110 ?

**Comment by TheLastProject** [comment]
I just realized I never paid attention to if the import/export was using internal or external storage and `READ_EXTERNAL_STORAGE` implies it would only be for external (although that would be weird, I guess they don't mean SD but external to the app). May need retesting on all API levels x.x

**Comment by developersu** [comment]
Hi,
Per you last changes, there could be a typo. Google kinda deprecated `READ_EXTERNAL_STORAGE` permission on API level 32, not 23, as noted:

https://github.com/CatimaLoyalty/Android/blob/ad7e021928d62815727c9f6d05170f9a01bbf0e8/app/src/main/AndroidManifest.xml#L15C1-L15C107

Thank you for your work!

**Comment by TheLastProject** [comment]
Not a typo. It may only be deprecated since level 32, but Catima hasn't needed it since Android 7 due to other changes allowing access to specific files without storage permission if the file manager is used :)
