### ISSUE TITLE
View Images within Native Application

### ISSUE THREAD

**Issue by atharen** [CatimaLoyalty/Android#980]
Came about from the discussion of #977, the ability to open images in an user-installed image viewing app when long-pressing an image (or PDF-turned-image - #496) so extended zooming, dragging, etc. become possible.

Use-case: I have some pictures which cannot be fully shown at 100%, but require more zoom. I would say if I were to hold the image, it should give me the option to open it in the native app.

**Comment by androlover98** [comment]
I would like to work on this issue. Could I get a detailed explanation about the ask here?

As far as I understood the issue, long pressing on the image in zoom mode (following screen) should trigger a prompt to open an app picker:
![Screenshot_20220926-231147_Catima](https://user-images.githubusercontent.com/24232447/192345088-a3bb3624-5853-4920-a197-74d8694a2066.jpg)

**Comment by TheLastProject** [comment]
Yeah you understood it right :)

I think maybe just always on long-press, as we don't do anything on long-press yet. I think forcing users to use fullscreen mode first when they know it won't fit could be a bit annoying.

**Comment by androlover98** [comment]
Understood! But should the change override the current behaviour of scrolling to the next available photo in the carousel?

**Comment by TheLastProject** [comment]
Oh, I completely forgot I had it set to also swipe to the next entry on long-press.

I think offering to open the native viewer on long-press makes more sense, so let's replace that yeah :)

**Comment by androlover98** [comment]
Now that I understand the requirement, I would like to work on this issue for Hacktoberfest. Please assign it to me.
