### ISSUE TITLE
Android 13 compat: Use new language support

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#991]
Google changed how multi-language support should work: https://developer.android.com/about/versions/13/features#app-languages

Marking this "good first issue" not because it'll necessarily be easy, but because the scope of it is very well-defined and if Google's documentation isn't clear enough most likely there is a LOT of examples on sites like StackOverflow.

**Comment by criticalAY** [comment]
i am working on it

**Comment by criticalAY** [comment]
I tried changing the language from Settings>Language and Input it was working fine. Could you please explain it a little better?

**Comment by TheLastProject** [comment]
Android 13 should allow you to change Catima's language from Android Settings instead of just Catima settings: https://www.androidpolice.com/android-13-dp2-per-app-languages-live/

**Comment by obfusk** [comment]
@TheLastProject I think this can be closed now that #1447 is merged?
